### ISSUE TITLE
Can't login with password sync disabled

### ISSUE THREAD

**Issue by miken32** [Adldap2/Adldap2-Laravel#108]
Very (very) new to Laravel, so apologies if this is something simple.I'm working with the [intro tutorial](https://laravel.com/docs/5.2/quickstart-intermediate) for now, and I [configured everything](https://github.com/Adldap2/Adldap2-Laravel/blob/master/quick-start.md) for LDAP authentication, using the instructions for Laravel 5.2. When attempting to login, I could see my server being queried, and LDAP users being inserted into the database, but I kept getting redirected back to the login page. When I changed password sync to true, it started working just fine.

**Comment by stevebauman** [comment]
This isn't an issue with your application. This is a bug on my end, thanks for the report!

This is due to the `validateCredentials()` method here: https://github.com/laravel/framework/blob/7642f12d7199456e5bf634a3e449023e3ee0160d/src/Illuminate/Auth/EloquentUserProvider.php#L114

Fix will be out momentarily.

**Comment by stevebauman** [comment]
Fixed in `v2.0.10`, please run `composer update`, thanks!
