### ISSUE TITLE
Perform actions as the logged in user

### ISSUE THREAD

**Issue by Rutafar** [Adldap2/Adldap2-Laravel#139]
Hello,

I am trying to make a website where the administators can register new users, however everyone can register a new user due to the fact that it is using the Administrator's credentials given in the config file to do that. 
I saw in the [documentation](https://github.com/Adldap2/Adldap2/blob/master/docs/authenticating.md#binding-as-authenticated-users) that you can bind a user but when I do that if I call Auth::check() it returns false.
I also wanted to bind a user so that it would be recorded in the active directory who made the change.
Do I have to do my own middleware?
I apologize if this has been answered before but I didn't find it.

Thanks in advance.

**Comment by stevebauman** [comment]
Hi @Rutafar,

This issue is related to #91. Please see my comment for further reasoning on why administrator credentials are required to import users upon login:

https://github.com/Adldap2/Adldap2-Laravel/issues/91#issuecomment-216922475

To perform your own custom authentication logic, you'll need to write your own method of creating users on a successful bind attempt.

For example:

```php
public function (LoginRequest $request)
{
    if ($this->adldap->bind($request->username, $request->password, true)) {
        $user = User::create(['attributes...']);

        Auth::login($user);

        return redirect()->to('dashboard');
    }
}
```

**Comment by Rutafar** [comment]
Ok thank you, I'll try that.
