### ISSUE TITLE
Filter login errors to blade

### ISSUE THREAD

**Issue by poxin13** [Adldap2/Adldap2-Laravel#163]
Hello, First all - thank you for this package! I have everything working great on Laravel 5.3.

I have a limitation filter setup to restrict login to Domain Admins. This is working great however when a non domain admin attempts to login the error being reported is 'These credentials do not match our records'. 

Instead, is there a way to get the error back from AD and forward that? I'd imagine it would say something instead like this user does not belong to domain admins, etc. I'm using the default make:auth artisan views.

```blade
@foreach ($errors->all() as $error)
    <li>{{ $error }}</li>
@endforeach
```

**Comment by stevebauman** [comment]
Hi @poxin13,

Unfortunately this probably wouldn't be possible. This is due to the fact that we try to *find* the user first, *then* try to bind to your LDAP server with the attributes from that returned user:

 https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/AdldapAuthUserProvider.php#L187

This gives us the ability to configure which attribute a user logs in with (whether it be their uid, mail, samaccountname, etc.).

When that search goes to your LDAP server with your limitation filter attached, it will return no results, indicating that the user doesn't exist, so we bail out of authentication and return false:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/AdldapAuthUserProvider.php#L191

Since no bind attempt is made until a user is found, there's no error of any sort we can work with to see why authentication failed.

**Comment by stevebauman** [comment]
You could however, create your own custom validation rule which queries your LDAP server for the requested username, and will return false if the user isn't apart of the domain administrator group?

```php
Validator::extend('administrator', function($attribute, $value, $parameters, $validator) {
    $user = Adldap::search()->users()->where(['samaccountname' => $value])->first();

    return $user->inGroup('Domain Administrators');
});
```

**Comment by poxin13** [comment]
Ah, I understand how the flow works now. Thanks for the suggestion on the custom validation rule, that will work fine, good idea 👍
