### ISSUE TITLE
Issue - Laravel 4 

### ISSUE THREAD

**Issue by anilskalyane** [Adldap2/Adldap2-laravel#2]
Laravel 4 is not supporting

**Comment by stevebauman** [comment]
This is intended. Laravel 4 was released 2 years ago and 5.1 is LTS. I may add L4 support, but I'm still unsure. I'll label this as an enhancement and keep it open for the time being.

**Comment by stevebauman** [comment]
With the current implementation of the authentication driver, this would be difficult to provide support for both laravel 4 and 5. Laravel 4 also supports a lower PHP version (5.3 instead of 5.4), which would create difficulties for the actual Adldap library. I do not intend to create a Laravel 4 version. Sorry!
