### ISSUE TITLE
How to get displayname

### ISSUE THREAD

**Issue by georgehk** [Adldap2/Adldap2-Laravel#214]
hello Steve,

Would you please help me how to get displayname and show this attribute in the view?

for example
{{ Auth::user()->displayname()}}

much appreaciate for your help.

Cheers,

**Comment by georgehk** [comment]
I figure out changing  in adldap_auth.php as follow:

    'sync_attributes' => [
        'name' => 'displayname',
    ],

but im wondering what happen if i want to bring more attributes for example email address.

**Comment by stevebauman** [comment]
If `email` is in your `username_attribute` to retrieve users (by default, this is how it's configured https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Config/auth.php#L58), then it's synced automatically.

Otherwise, just insert another key => value pair indicating you'd like it synchronized:

```php
'sync_attributes' => [
    'name' => 'displayname',
    'email' => 'mail',
],
```
