### ISSUE TITLE
adldap:import, groups and deletion

### ISSUE THREAD

**Issue by eleftrik** [Adldap2/Adldap2-Laravel#222]
In the README: "_Users are never deleted from the import command, you will need to clear users regularly through your model_", but there is `--delete` option, which deletes users who has been disabled, right? (I think README hasn't been updated).

This option works but, in my case, I import users belonging to a group, e. g. `php artisan adldap:import --filter="(memberOf=CN=mygroup,CN=Users,DC=my,DC=company)" --delete=true`

When a user gets removed from `mygroup`, I would like (soft) delete it. Is there a way to be notified about this changes?

Thanks

**Comment by stevebauman** [comment]
Hi @eleftrik, this hasn't been updated in the docs because the feature isn't contained in an actual release yet (`v7.0` coming shortly!). It also **only** soft deletes, and never actually removes the record.

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Commands/Import.php#L213-L236

> When a user gets removed from mygroup, I would like (soft) delete it. Is there a way to be notified about this changes?

Unfortunately you would have to implement this yourself. I personally wouldn't implement this as a feature since one typo in the distinguished name of the custom filter could cause soft deletes of all of your user models.
