### ISSUE TITLE
How handle password change/reset?

### ISSUE THREAD

**Issue by jmanuelemus** [Adldap2/Adldap2-Laravel#252]
I'm developing an application and using Adldap2 as auth driver. How the application could handle password change via Password::broker and/or user password change webpage?.  What happen when password is changed on User model, is it synced?

**Comment by stevebauman** [comment]
Hi @jmanuelemus,

Password changes are not synced. If you change the password on a synchronized User model, it will simply be overwritten with a random 16 character hashed password, or the users AD password (if you have `password_sync` enabled in your `config/adldap_auth.php` file).

I have no plans to implement password resets / changes with the driver. Due to LDAP limitations / configurations, this would be a headache to manage, and should be implemented of a per-project basis.

You can easily implement this yourself though, especially if you enable the `bind_user_to_model` option, you can change the users AD password through it:

```php
$user = Auth::user();

try {
    $user->adldapUser->changePassword($oldPassword, $newPassword);

    // Successfully changed the users password.
} catch (\Exception $e) {
    // Changing Password failed.
}
```
