### ISSUE TITLE
Fail to authenticate user with Multiple LDAP Connections

### ISSUE THREAD

**Issue by superbull** [Adldap2/Adldap2-Laravel#259]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0.0
- PHP Version: 7.0.11

### Description:
Follow the instructions in [Using Multiple LDAP Connections](https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/multiple-connections.md), the user within the **other-connection** will failed to authenticate.

### Steps To Reproduce:
1. Follow the instructions in [Using Multiple LDAP Connections](https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/multiple-connections.md).
2. Try to login with an user within the **other-connection**.

### Reason
The **resolver** is cached for the first connection setting. See the [code](https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Traits/UsesAdldap.php#L59). So that the resolver with the first connection setting will always be returned even you change the connection config later:
```php
Config::set('adldap_auth.connection', 'other-connection');
```

### Solution suggestion
1. Return new resolver every time:
```php
trait UsesAdldap
{
    ...

    public function getResolver()
    {
        $resolver = config('adldap_auth.resolver', Resolver::class);

        return new $resolver($this->getLdapProvider());
    }

    ...
}
```

2. Find some way to call `setResolver(null)` after change the config value of  `adldap_auth.connection`.

**Comment by stevebauman** [comment]
Thanks @superbull, looking into this now.

I believe this is due to not creating a new resolver every time it's called:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Traits/UsesAdldap.php#L50-L60

Will have a fix out soon.

**Comment by stevebauman** [comment]
This might be difficult to implement... Using multiple connections could break other features.

For example, if you're using the `NoDatabaseUserProvider`, and you authenticated through a second connection, you'd be logged out on the second request because it would utilize your default resolver to retrieve the user by their ID:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Auth/NoDatabaseUserProvider.php#L9-L21

**Comment by ethanhann** [comment]
Any progress on this?

**Comment by stevebauman** [comment]
@ethanhann No unfortunately. Haven't been able to spend much time on implementing this, but definitely accepting PRs!

**Comment by psraghul** [comment]
@stevebauman 

Any updates on this ?

**Comment by stevebauman** [comment]
Hi @psraghul, no unfortunately. still nothing yet. This is difficult to implement and document. Accepting PR's as always though if someone has time to take a crack at this.

**Comment by yakatz** [comment]
I am going to take a stab at this. I think the only way would be to save the connection used in the session store.

For the record, the old documentation can be found here: https://github.com/Adldap2/Adldap2-Laravel/blob/f025d674c3573e97a43a15d5efca1279e9d7e90e/docs/auth/multiple-connections.md

**Comment by Machecek** [comment]
@stevebauman any progress on this issue?

**Comment by yakatz** [comment]
My boss decided we should move this down the priority list. I am still trying to get to it.

**Comment by stevebauman** [comment]
I think you'll first have to determine what user is authenticating and set the authentication connection at run-time before calling `Auth::attempt()` in the build in Laravel `LoginController`.

After authentication has been successful, as @yakatz has said, you'll need to store the connection name in the session, and set it at run-time depending on the authenticated user (using a middleware likely).

LoginController:
```php
public function login(Request $request)
{
    $connection = str_contains($request->email, '@domain-b.org') ? 'connection-b' : 'connection-a';

    Config::set('ldap_auth.connection', $connection);

    if (Auth::attempt($request->only(['email', 'password'])) {
        // ...

        Session::put('ldap.connection', $connection);

        return redirect('/');
    }
}
```

Middleware:

```php
/**
 * Handle an incoming request.
 *
 * @param \Illuminate\Http\Request $request
 * @param \Closure                 $next
 *
 * @return mixed
 */
public function handle($request, Closure $next)
{
    if ($connection = Session::get('ldap.connection')) {
        Config::set('ldap_auth.connection', $connection);
    }
}
```

I haven't tried this, but it should work :tm:

**Comment by yakatz** [comment]
It is more complicated than that for us because one of our LDAPs is IPA and the other is Windows, so the entire ldap_auth config needs to be made multi-connection aware. (In the mean time, I need to override each config item manually.)

**Comment by stevebauman** [comment]
@yakatz Oh definitely, that would be much harder to manage...

**Comment by stevebauman** [comment]
Closing this one out. I could allow this and have configuration values for it, but there's so many things that would need to be configurable. It would be extremely hard to offer this type of configuration with different scenarios. In my mind it's better to develop this on the application side.

For example, say we have multiple LDAP auth points.

- What if one isn't reachable / goes down?
- Should both LDAP auth points be used in the same request? Or should they have separate endpoints to authenticate against?
- What if a dev is using just a `username` for authentication and there's a username conflict? How would we handle this in the backend when synchronizing / importing users?
- How would we determine who belongs to which domain?
- How would we debug each LDAP auth point? (This is already a pain for current users with one domain, as they currently find it difficult to debug as is)

I'll absolutely consider PR's and any suggestions on implementation, but I can't invest time into this myself because I personally wouldn't be able to test it easily, have it configurable and document the entire process so it's easier for other developers.
