### ISSUE TITLE
OpenLdap authentication requires full dn

### ISSUE THREAD

**Issue by Douglasdc3** [Adldap2/Adldap2-Laravel#269]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3
- PHP Version: 7.1

### Description:

OpenLdap requires a full DN to bind the user. When going through the Laravel's guard flow at no point is the full DN build. 

For the administrator account binding this is done by setting it in the .env file. I think this should be part of the framework too automatically build the full DN from the config. 

Work around now is override before the form goes through Guard to find the user in OpenLDAP & get the 'dn' attribute.

Changing the Adldap\Laravel\Auth\Resolver  to

```  
    /**
     * {@inheritdoc}
     */
    public function authenticate(User $user, array $credentials = [])
    {
//        $username = $user->getFirstAttribute($this->getLdapUsername());
        $username = $user->getDn();

        return $this->provider->auth()->attempt($username, $credentials['password']);
    }

```

Not sure if it is intended that people override this class for OpenLdap or if you have a plan to include openLdap Provider in the future. 

### Steps To Reproduce:

* Setup a bare laravel app
* Include adldap2-laravel
* configure the openldap server
* Use the default laraval authentication form
* change view template "email" to "username"
* change the LoginController override the username method `return 'username‘; `
* attempt to login
* Login will fail with "invalid DN" message coming from ldap_bind method

**Comment by stevebauman** [comment]
Hi @Douglasdc3,

This is the purpose for the `account_suffix`, `account_prefix`, `admin_account_suffix` & `admin_account_prefix` options:

```php
'account_prefix' => 'uid=',
'account_suffix' => ',ou=users,dc=acme,dc=org',

'admin_account_prefix' => 'uid=',
'admin_account_suffix' => ',ou=administrators,dc=acme,dc=org',
```

This builds the DN and allows OpenLDAP users to login by their username.

Unfortunately the limitation of this is that all regular user accounts must be located under the same OU.

Having an `OpenLdapAuthProvider` would cause confusion since I'd have to create two of them. One for allowing developers to import the user into their local database, and another for developers who don't want a local record in their database.

If you're able to implement this in the current providers that has compatibility with both ActiveDirectory and OpenLDAP, definitely let me know!

**Comment by Douglasdc3** [comment]
Hi @stevebauman 

This partly fixes the problem. When using the `cn` the above proposed fix would work as soon as the ldap server is configured fro another property it complains about invalid credentials. 

The OpenLDAP  server I have to integrate with and the current user base uses `uid` as primary authentication method. 

It would be hard to get into the current could without an ugly if statement. 
Another option would be to defer the username to RDN to it's own class. In my opinion this makes sense as the DN syntax / favour depends on the type of Active Directory implementation. 


Also from what I could see in the code https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Auth/Resolver.php#L63-L68 is where the reference to the full DN is lost

**Comment by stevebauman** [comment]
> The OpenLDAP server I have to integrate with and the current user base uses uid as primary authentication method.

You would just change the `ldap` username in your configuration file here:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Config/auth.php#L134

```php
'ldap' => 'uid',
```

> Also from what I could see in the code https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Auth/Resolver.php#L63-L68 is where the reference to the full DN is lost

I'm not sure what you mean by "*is where the reference to the full DN is lost*".

The username is passed into the Adldap Providers `Guard::attempt()` method [here](https://github.com/Adldap2/Adldap2/blob/master/src/Auth/Guard.php#L60-L82), which assembles their username with the account prefix and account suffix, which essentially will be authenticating the user by their distinguished name.

For example, I recently assisted a user to authenticate against a public OpenLDAP server with the following configuration: https://github.com/Adldap2/Adldap2-Laravel/issues/240#issuecomment-284398713

Public OpenLDAP Server: http://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/

Adldap2-Laravel has no issues authenticating against it with the configuration in the comment I've linked above.

**Comment by Douglasdc3** [comment]
Thanks Steve for the help I think I'm hitting this:

> Unfortunately the limitation of this is that all regular user accounts must be located under the same OU

When I limit to one OU it does work. I wrote a custom class which is a wrapper around Resolver which will suffix the username with it's correct OU and use the account prefix/suffix config to do the rest.

I wonder if a cleaner way exists to fix this issue.

**Comment by stevebauman** [comment]
Hi @Douglasdc3, implementing this now for compatibility with OpenLDAP: https://github.com/Adldap2/Adldap2-Laravel/commit/29008aa5e18b97690bf7ca995f8abb65e8cc93c0

This will exist in a new minor version due to the configuration changes.

Working on some tests and this will be released.

It will allow OpenLDAP users to authenticate users in any OU, and solve more OpenLDAP compatibility issues.

**Comment by ThomHurks** [comment]
@stevebauman I'm working on a Laravel project that requires OpenLDAP authentication and we're looking at using Adldap2-Laravel. We're currently having some issues getting the authentication to work, and it might be that this change helps us as well. Are you planning to tag a new release soon? In the mean time I think we can try pulling the latest version manually and check if it works better. Thanks for your work!

**Comment by stevebauman** [comment]
Hi @ThomHurks, this change is live in the current `master` branch. You will be able to configure how LDAP users are discovered and which attribute is used for authenticating against your LDAP server:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Config/auth.php#L123-L159

A new release will be tagged this week. I'm just working on documentation at the moment. Due to breaking changes it will be a `v4.0.0` release.

Closing this as it's been resolved in the master branch and it cannot be resolved without breaking changes.

**Comment by ThomHurks** [comment]
Thanks @stevebauman!
