### ISSUE TITLE
Binding using CN=username not using samaccountname

### ISSUE THREAD

**Issue by ArabAgile** [Adldap2/Adldap2-Laravel#293]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0.*
- PHP Version: 7

When binding user, the $bind_rdn or username value is set to either '_samaccountname_' or '_userprincipalname_'. So when I'm logging it as johnuser and 123456 as password, Adldap2 library using these values for binding. 
`ldap_bind($ldap, 'johnuser', '123456')`

However, I need to force login to use the full Distinguished Name like:
`CN=Johnuser,OU=Staff,DC=ACME,DC=COM`

**So how to achieve this?**

Previously, I'm using Drupal for LDAP, and Drupal at the FIRST TIME will search for the user using admin binding, and get the DN for the user, then will creates the user in the database with extra record which is (user_dn) and the values is CN=Johnuser,OU=Staff,DC=ACME,DC=COM.

So for the next login, will use this **saved** DN for login, instead of using the raw username _samaccountname_.

**Is that good practice or not?**

Another issue I'm facing with current authentication (after many hours of debug) is that _Adldap2-Laravel_ will do **TWO** LDAP binding calls. One using the admin binding, and the other using the username & password binding.

However, I created pure PHP ldap_bind() calls to check what's going on. I've noticed that when passing the username _samaccountname_ and password it fails with "**Invalid Credentials**" error.

But it **success** when passing the _userprincipalname_ johnuser@acme.com as username.

HOWEVER, the most interesting part - at least to me - is that I was able to bind using the **FULL NAME** of the user! So if the username is 'Mr. John Doe', and the password is '123456', It can BIND surprisingly with no errors!

I'm new to LDAP, so is that correct scenario? Is my company's LDAP configured correctly? And if AD is missing configuration how to fix this?

The previous investigations lead me to this next solution. I'll use the following configurations:
```
'usernames' => [
        'ldap' => '**userprincipalname**', // previously sAMAccountName
        'eloquent' => 'username',
],
```

In this case, I'm passing the UPN as the username _johnuser@acme.com_, and I can login successfully!.

However, the NEXT login to Laravel will fail due to:
`Integrity constraint violation: 1062 Duplicate entry 'John Doe' for key 'users_username_unique' (SQL: **insert** into `users` ... VALUES ...`

Clearly it's inserting the user again, not updating the old one!

I'm really suffering from this. I need simply to use LDAP Auth out of the box without writing custom library from scratch, so what's wrong?

Thank in advance.
Arab

**Comment by stevebauman** [comment]
Hi @ArabAgile, I'll go through each of your questions and answer them individually. If I've missed an answer to one, please let me know!

1. 
> When binding user, the $bind_rdn or username value is set to either 'samaccountname' or 'userprincipalname'. So when I'm logging it as johnuser and 123456 as password, Adldap2 library using these values for binding.
ldap_bind($ldap, 'johnuser', '123456')
> 
> However, I need to force login to use the full Distinguished Name like:
CN=Johnuser,OU=Staff,DC=ACME,DC=COM

Inside your `config/adldap_auth.php` file, you can configure the username you authenticate users with:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Config/auth.php#L119-L152

If you need to login users by their distinguished name, you need to insert that attribute into the `ldap` key:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Config/auth.php#L119-L152

You can either use `dn` or `distinguishedname` to login users via their full DN.

However, this means you'll need to modify your `create_users_table.php` migration file to include this `dn` column, then modify the `eloquent` attribute to match this columns name.

> Another issue I'm facing with current authentication (after many hours of debug) is that Adldap2-Laravel will do TWO LDAP binding calls. One using the admin binding, and the other using the username & password binding.

It will actually perform 3 binding calls for an `Auth::attempt()` using the `adladp` auth driver (if `auto_connect` is set to `true` inside your `config/adldap.php` file).

- Once for binding as your configured administrator account in your `config/adldap.php` file (this account is used for locating the user who is trying to authenticate, making sure they actually exist as an LDAP user in your directory)
- Another for binding as the user trying to authenticate if they are found in your directory
- Then once more for re-binding as your configured administrator so you can perform any LDAP calls needed during the same request

> However, I created pure PHP ldap_bind() calls to check what's going on. I've noticed that when passing the username samaccountname and password it fails with "Invalid Credentials" error.

This is because you need to `ldap_bind()` with your users `userprincipalname`. This name contains the samaccountname of your user, and the suffix of your domain. For example

```
sbauman@corp.acme.org - My userprincipalname

sbauman - My samaccountname 

@corp.acme.org - My domain suffix
```

> HOWEVER, the most interesting part - at least to me - is that I was able to bind using the FULL NAME of the user! So if the username is 'Mr. John Doe', and the password is '123456', It can BIND surprisingly with no errors!

This is strange that you were able to bind using the full name of your user account. Did you configure this in your `config/adldap_auth.php` file? Maybe using:

```php
'usernames' => [

    'ldap' => 'cn',

    'eloquent' => 'username',
]
```

If you used this configuration above, you would be able authenticate with your full name.

> Clearly it's inserting the user again, not updating the old one!

Sounds like you changed the `config/adldap_auth.php` configuration, authenticated, changed the config again, and re-authenticated which failed because it tried to create a new user that already exists in your database.

This configuration isn't meant to be changed after deployment.

> I'm really suffering from this. I need simply to use LDAP Auth out of the box without writing custom library from scratch, so what's wrong?

Once you take a peek into the source of Adldap2-Laravel, it's not very complicated to debug what might be going on.

I would edit the source files directly and dump / die (using the Laravel helper `dd()`) some variables to debug what might be going on, as I have no idea which LDAP directory you're working with, nor your configuration of your Laravel application, or even Adldap2.

**Comment by ArabAgile** [comment]
Hi @stevebauman, your response is really really appreciated.

In answer 1, I don't know the `distinguishedname` of a user, so I'm expecting the first 'admin' LDAP connection to do the a call to get the user's `distinguishedname`, then insert the user in `users` table, then authenticate the user using the saved `distinguishedname`. Is this a feature you're interested to add it?

Regarding point 3:  

> This is because you need to ldap_bind() with your users userprincipalname. This name contains the samaccountname of your user, and the suffix of your domain. 

If that's the case, then why the library don't append the domain suffix by itself when selecting _samaccountname_ as login?
Is it something I've to change from my LDAP server configuration to allow the login using sameaccountname & password?

As a workaround, I created a field in `users` table containing `principal_name`, then I used this configurations
```
'usernames' => [
        'ldap' => 'userprincipalname', 
        'eloquent' => 'principal_name',
],
```

So when logging in, user will enter only `sameaccountname`, and the controller will take care of adding the domain `suffix` to generate the final `userprincipalname`. But I think there's simpler solution!


The point 4 is not strange in library, as I did it in pure PHP not by using the library so you can ignore it please. But is that logical - from LDAP server configuration side - to allow login using fullname?

In point 5, I did the following config
```
'usernames' => [
        'ldap' => 'userprincipalname', 
        'eloquent' => 'username',
],
```

So clearly I've to replace `username` with `principal_name` as per the workaround mentioned above.

In brief:
1. Is it possible to get the user's `dn` then authenticate the user based on `dn` out of the box?
2. Is it something in server configuration to allow authenticate using `samaccountname` & password?
3. What steps required to enable `userprincipalname` authentication, but the user will enter only the username (samaccountname), and Laravel (controller, etc...) will take care of appending the @domain.org to formate the right `userprincipalname`.

Thanks in advance.

**Comment by stevebauman** [comment]
> If that's the case, then why the library don't append the domain suffix by itself when selecting samaccountname as login?
Is it something I've to change from my LDAP server configuration to allow the login using sameaccountname & password?

This is something you need to configure in your `config/adldap.php` file. This is why the `account_suffix` and `account_prefix` option exists:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Config/config.php#L103-L114

> 1. Is it possible to get the user's dn then authenticate the user based on dn out of the box?
> 2. Is it something in server configuration to allow authenticate using samaccountname & password?
> 3. What steps required to enable userprincipalname authentication, but the user will enter only the username (samaccountname), and Laravel (controller, etc...) will take care of appending the @domain.org to formate the right userprincipalname.

These are conflicting questions, as it sounds like you're wanting to authenticate with three different user attributes?

I believe your second question is what you're truly after. Here's how you can do this:

```php
// config/adldap_auth.php

'usernames' => [
        'ldap' => 'samaccountname', 
        'eloquent' => 'username',
],
```

```php
// config/adldap.php

 'account_suffix' => '@corp.acme.org',
````

Notice how were going to use the users `samaccountname` for discovery of the user, but during authentication to your LDAP server, your configured `account_suffix` will be appended to this account name, making the users `userprincipalname`.

For example, when I try to login to your application with my username `sbauman`, Adldap2 will look for a user with the `samaccountname` of `sbauman`. Then, it will try authenticating me against your LDAP server with `sbauman@corp.acme.org` because of the `account_suffix` option being set.
