### ISSUE TITLE
Login fallback - Don't throw bind exceptions when server unavailable

### ISSUE THREAD

**Issue by balaram536** [Adldap2/Adldap2-Laravel#295]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0
- PHP Version: 7.1

### Description:
I'm trying to use this package and it looks really nice.
but i have one issue .

-i have two types of users. one type of user i.e employees of organization they will 
authenticate through ldap and other types of user i.e non-employees of organization  they will authentication using the password in our local database which is not ldap.
- the above explanation works when i using the application in organization network.

- when i tried to use out side of network it gives the error can't connect to ldap server.

- in my case if it cannot connect to ldap server without giving the error it should check in to our local database and login.

can you help me with this.

thanks.

**Comment by pulasthibandara** [comment]
Ran in to the same issue. Our AD server went down due to a network shortage and the app failed to fall back to the database users. I think catching **Adldap\AdldapException** or **Adldap\Auth\BindException** in the **DatabaseUserProvider** should fix this issue.

**Comment by stevebauman** [comment]
Hi @balaram536, this isn't the intended usage of the fallback option.

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/fallback.md#login-fallback

>- You may have some active directory users and other users registering through the website itself (user does not exist in your AD).
>- Local **development** where your AD server may be unavailable

If your AD server is down and is unable to be contacted, the exception is meant to be thrown.

The original idea behind the fallback option, was to fallback to your local database **only if** LDAP authentication fails, not if it can't be contacted or connected to.

Otherwise, you would have no idea whether you connection works, and you'd be wondering why you're not able to login with your AD credentials. This would generate a ton more user confusion.

I'll see if there's an elegant solution here to accompany both use cases.

**Comment by pulasthibandara** [comment]
Hey @stevebauman, Will it be possible to introduce a configuration option and default it to not to catch BindExceptions? So that when you go into production you can enable fallback when AD server is not available.

**Comment by stevebauman** [comment]
@pulasthibandara, It may not be a configuration option, I'm not sure yet. However, I will definitely be introducing this. Keep you're eyes peeled on commits, will be working on this shortly :).

**Comment by pulasthibandara** [comment]
Thanks @stevebauman , Looking forward for this. (no pressure :D)
