### ISSUE TITLE
Retrieving LDAP User

### ISSUE THREAD

**Issue by chrisbaswell** [Adldap2/Adldap2-laravel#3]
I know you're actively developing this so this is more of a question than an issue.  You previously had retrieveByCredentials authenticating against LDAP first and then returning a Laravel User Model.  In your recent changes you're searching LDAP before authenticating.  I'm wondering your reasoning behind this.  

~~Also if you were to take this approach it would be beneficial to map an input name to a searchable LDAP attribute i.e. my login form has username as the field and it needs to be mapped to the samaccountname attribute to find an account.  As it stands currently, you're just looping through the credentials and querying with the key and value.  Since username isn't a searchable key, this is currently failing for me.~~ Just noticed the documentation has been updated to reflect this

I'm not nearly as skilled at development but I'd be happy to assist in any way possible with this package.  I don't know how advanced you were wanting to get with this either but in my particular implementation I'm wanting to redirect to a "welcome to the company" registration page if it's their first time logging on.  That may be out of your planned scope but it's a thought.

This is an excellent package so far though.  Much better approach then others I've seen.

**Comment by stevebauman** [comment]
Hi, the reason I've implemented searching before authenticating was to allow developers to use other user attributes for logging in (mainly email since email is the default login attribute in laravel). This is pretty much identical to the way the `EloquentUserProvider` auth driver works ([Line 87](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Auth/EloquentUserProvider.php#L87)). This also sort of provides a verification that the user actually exists before trying to authenticate against your AD server.

I personally just thought it would have been finicky to have a configuration value that mapped the html input name to an active directory attribute.

As for your other question, you can use the Laravel model of the user to provide an approach for this. You can use the `wasRecentlyCreated` property to see if the user was just created on the current request. This would then return false on all other requests.

https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Eloquent/Model.php#L194

For example:

```php
$user = Auth::user();

if($user->wasRecentlyCreated)
{
    // Display welcome page
} else
{
    // Redirect to standard page
}
```

**Comment by chrisbaswell** [comment]
Thanks for your reply. 

You're right it might get a little confusing to add that as a configuration option.  And the search then login approach makes more sense after looking at the Eloquent implementation.

Thanks for pointing out that property on the model.  I struggled a little trying to get it to work. I tried adding the following to the `Authenticate` middleware but I don't think I can access the User instance that's created during the authentication process.  The `wasRecentlyCreated` property was false.

    if($request->user()->wasRecentlyCreated)
            return redirect('welcome');

So I added a method that is automatically fired from the  `AuthenticateUsers` trait after the user has been authenticated.  That seemed to reference the user that was just created.

    public function authenticated(Request $request, $user)
    {
        if($user->wasRecentlyCreated)
            return redirect('welcome');

        return redirect()->intended($this->redirectPath());
    }

Not sure why the middleware approach wouldn't work though.  Could you shed any light on that?  Sorry this tangent isn't really related to your package any more.

**Comment by stevebauman** [comment]
No problem at all. Also for your other question, did you try using `$this->auth->user()`?
