### ISSUE TITLE
Authentication denied

### ISSUE THREAD

**Issue by dododedodonl** [Adldap2/Adldap2-Laravel#334]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0.4
- PHP Version: 7.0

### Description:
When authenticating, Adldap2 searches anonymously ([does not bind as administrator](https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Auth/Resolver.php#L23)) if the user exists before making an auth attempt. This means records have to be searchable anonymously, which could be unwanted.

**Comment by stevebauman** [comment]
Hi @dododedodonl, you have to call `ldap_bind` for an anonymous bind / search to take place.

Otherwise, you won't receive any search results. This is due to muted exceptions when queries are ran against your LDAP connection:

https://github.com/Adldap2/Adldap2/blob/master/src/Query/Builder.php#L218-L220

If `auto_connect` is enabled, Adldap will bind to your server. No anonymous searching or binding takes place unless you call `$provider->auth()->bind()` method manually:

https://github.com/Adldap2/Adldap2/blob/master/src/Auth/Guard.php#L60

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/AdldapServiceProvider.php#L72-L106
