### ISSUE TITLE
HasMemberOf trait not working

### ISSUE THREAD

**Issue by dododedodonl** [Adldap2/Adldap2-Laravel#335]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 3.0.4
- PHP Version: 7.0
- LDAP Type: OpenLdap

### Description:
The HasMemberOf trait does not work with openldap memberOf overlay by default, because you have to specifically request the memberOf attribute. This is not done by the authentication resolver (so the attribute does not exist when the trait searches for it).

**Comment by stevebauman** [comment]
Hi @dododedodonl, not sure what you mean?

All attributes are selected by default, unless you specify them in a [Scope](https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/scopes.md).

**Comment by dododedodonl** [comment]
When selecting groups, this does not work: `$request->user()->getGroups()`. I have to do this `Adldap::search()->select(['memberof'])->findByDn($request->user()->getDn())->getGroups()`.

**Comment by stevebauman** [comment]
I can't replicate this issue. However this could be an OpenLDAP related bug.

I'll have to investigate further.

**Comment by dododedodonl** [comment]
When I execute a local `ldapsearch` without any attributes supplied, the `memberOf` attribute is not returned. When I explicitly retrieve the `memberOf` it is. Maybe it is a bug in the memberOf overlay in openldap or a bug in my setup.

**Comment by stevebauman** [comment]
Great thanks for looking this up! I'm going to have this fixed in a moment.

**Comment by dododedodonl** [comment]
What is the status on this issue?

**Comment by stevebauman** [comment]
Hi @dododedonl,

This hasn't been implemented yet. I think this issue slipped my mind due to it relating to the root Adldap2 repository.

I'm completely open to PRs, otherwise it will be fixed this weekend (out of the country until then).

Thanks for your patience! :)

**Comment by stevebauman** [comment]
Hi @dododedodonl, this has been fixed in the master branch (https://github.com/Adldap2/Adldap2/commit/b82424960cd2c7336bfcefdeec3505136d23dab6), however you will need to create a scope to include this for Adldap2-Laravel.

Since requesting the `memberof` field can affect performance minimally, I can't include it in a default scope for Adldap2-Laravel.

I will create an OpenLDAP specific scope that developers can insert into their `adldap_auth.php` file to request this attribute so you will be able to utilize the users groups for authenticated users.

I have created an issue for this feature and will close it once implemented: https://github.com/Adldap2/Adldap2-Laravel/issues/433.
