### ISSUE TITLE
Help for the scope search??

### ISSUE THREAD

**Issue by Albvadi** [Adldap2/Adldap2-Laravel#343]
- Laravel Version: 5.4.25
- Adldap2-Laravel Version: 3.0.4
- PHP Version: 7.0.9

### Description:
Hi,
it´s possible handle a multiple options in the same scope??

My requeriment its:

- Only users with baseDN same as `ou=helpdesk,ou=departments,ou=company.com`
    - This it´s handle with: `$builder->in("ou=helpdesk,ou=departments,ou=company.com");`
- **OR** a special user with uid=special_user from other DN, for example: `ou=admins,ou=departments,ou=company.com`

How can I acomplish this with the builder??

**Comment by stevebauman** [comment]
Hi @Albvadi, this isn't possible with LDAP unfortunately.

When you perform a LDAP query, you need to set the depth of the search, this is what the `in()` method does. You can't set multiple OU's in one search. You'll need to query for attributes / groups instead of by OU.

There's an answer here that specifies that you can search by multiple OU's in ActiveDirectory:

https://stackoverflow.com/questions/9184978/ldap-root-query-syntax-to-search-more-than-one-specific-ou

However this relies being connected to a different port on your AD server and probably isn't worth trying to set up. The same difficulty most likely applies when using OpenLDAP.

I would apply a group to your users you'd like to allow authentication with, or you could set your scope to `ou=departments,ou=company.com`, then create a [Rule](https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/rules.md) to check their distinguished name and see if they're contained in the OU's you're looking for:


```php
namespace App\Rules;

use Adldap\Laravel\Validation\Rules\Rule;

class OuRule extends Rule
{
    /**
     * The LDAP user.
     *
     * @var User
     */
    protected $user;
    
    /**
     * The Eloquent model.
     *
     * @var Model|null
     */
    protected $model;
    
    /**
     * Determines if the user is allowed to authenticate.
     *
     * @return bool
     */   
    public function isValid()
    {
        $ous = [
            'ou=helpdesk,ou=departments,ou=company.com',
            'ou=admins,ou=departments,ou=company.com',
        ];

        return str_contains($user->getDn(), $ous);
    }
}
```

**Comment by Albvadi** [comment]
I stopped at the scopes and did not read any more...  :man_facepalming: 
You opened my eyes... Rules it's all I need.

I'm able to expand the scope n depths and with the Rules check anything with the data user..

Thanks as always for this awesome package, for all the options you had thinked for us and for your superb support!! 🙌

**Comment by stevebauman** [comment]
Thanks so much for your kind words @Albvadi! Appreciate it 😄 

No problem at all, I'm always happy to help with any questions at any time.
