### ISSUE TITLE
General Questions on Difficulty Debugging

### ISSUE THREAD

**Issue by byanke-pcn** [Adldap2/Adldap2-Laravel#353]
- Laravel Version: 5.4.28
- Adldap2-Laravel Version: Current
- PHP Version: 7.0.18

### Description:
I'm having difficulty getting this working with my company's AD server. We only need to allow users to log in and get information about themselves, and so I'm having trouble getting it working to bind as the user logged in and not as a network admin.

However, more generally, I'm trying to debug the connections, to see what PHP ldap commands are actually running on the low level to try and debug and get everything properly connected. 

Right now, I'm only seeing "These credentials do not match our records" along with nothing in the laravel logs, while I do submit a valid network credential (email/pw).

What is the best way to get more visibility into the library and debug login connection issues? I suspect I'm just not sending the right fields to the AD server, but I don't know what is even being sent...

**Comment by stevebauman** [comment]
Hi @byanke-pcn, the account you use as the `admin` account specified in your configuration will always be re-bound after a bind for an authentication attempt using the Adldap2 auth driver.

This is due to needing to bind to your LDAP server prior to the authentication request so we can retrieve the LDAP user authenticating using any attribute you wish.

This is also done so you can perform any operations on your LDAP server at any time through your application.

Do debug, I would simply dump and die (`dd()`) at certain points during the authentication attempt to see where it's failing. A good start would be dumping the returned user from the resolver in the `retrieveByCredentials()` method in the `DatabaseUserProvider` 

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Auth/DatabaseUserProvider.php#L94-L95

If the user is found, then try dumping inside the `validateCredentials()` method in the `DatabaseUserProvider` to see if the user is binding to your server successfully:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Auth/DatabaseUserProvider.php#L124-L151

**Comment by byanke-pcn** [comment]
Thanks, I will try those!

**Comment by stevebauman** [comment]
No problem! If you still encounter issues, please let me know and I'd be glad to help you out.

**Comment by byanke-pcn** [comment]
Excellent, thanks! 

I'm finding this lib exceedingly useful. Planning on using it for all our internal corporate projects.

**Comment by benyanke** [comment]
FYI, I consolidated my multiple github accounts, so my old account shows up as "ghost." I was the original author of this thread, and can be reached here in the future. Love this lib!
