### ISSUE TITLE
Follow-up to ticket #357 Authenticating with an incorrect password produces an error.

### ISSUE THREAD

**Issue by mslindow** [Adldap2/Adldap2-Laravel#358]
- Laravel Version: 5.4
- Adldap2-Laravel Version: 7.0 (I believe)
- PHP Version: 7.1.6

### Description: authenticating with an incorrect password causes an error:
I'm sorry, I should have added that we did set all permissions (777) on all directories from 'storage' on down. When would adldap2 have attempted to create the folders?
The error looks like this:
![image](https://user-images.githubusercontent.com/17485413/28327347-5bbbd1fe-6ba0-11e7-81d7-ffa903c21be0.png)

**Comment by stevebauman** [comment]
Hi @mslindow, this is due to the stock Laravel login rate limiter. You can see it's setting a `lock` variable to `true` since you've tried logging in too many times as well as trying to store your IP address and username you're authenticating with.

Unfortunately there isn't much I can suggest, as this is an application specific issue and doesn't relate to Adldap2. You can verify this by removing the adldap auth driver and try authenticating multiple times until you hit the rate limit.

I would suggest creating an issue on [Laravel's GitHub Repository](https://github.com/laravel/framework) or StackOverflow to see if they can help resolve this.
