### ISSUE TITLE
Can a windows AD restict connection on userprincipalname and block samaccountname

### ISSUE THREAD

**Issue by devplanete** [Adldap2/Adldap2-Laravel#372]
- Laravel Version: #5.4.30#
- Adldap2-Laravel Version: #3.0.5#
- PHP Version: #7.0#

### Description:
I have followed the installation from scratch tuto https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/quick-start.md (I use username instead of email field in DB and form) and I'm able to authentified user with userprincipalname.

But no way to authenticate user with their samaccountname. I have the standard "These credentials do not match our records." message of laravel like if the password is wrong.
So do you think that Windows AD can block authentication with other thing than userprincipalname?

### Steps To Reproduce:
In adldap_auth.php, I simply change in the 'usernames' section
   'ldap' => 'userprincipalname',
by
   'ldap' => 'samaccountname',

and in the 'sync_attributes' section
    'username' => 'userprincipalname',
by
  'username' => 'samaccountname',

And I clean users table before to try to logon.

Thanks for your help

**Comment by stevebauman** [comment]
Hi @devplanete, the `userprincipalname` is suggested as the attribute to use because it includes your domain suffix which is needed for authentication but is also usually the users email address.

For example, if my base dn is `dc=example,dc=com`, then my `userprincipalname` is `sbauman@example.com`.

To resolve your issue using the `samaccountname`, add your domain suffix to the `config/adldap.php` file under the `account_suffix` option:

```php
'account_suffix' => '@example.com',
```

Closing this as it should resolve your issue, but if it doesn't please let me know, thanks!

**Comment by devplanete** [comment]
Yes! you solve my issue. Thanks :)

**Comment by stevebauman** [comment]
Great! No problem at all :).
