### ISSUE TITLE
Undefined index: email using NoDatabaseUserProvider

### ISSUE THREAD

**Issue by entrique** [Adldap2/Adldap2-Laravel#387]
- Laravel Version: 5.5
- Adldap2-Laravel Version: 3.0.5
- PHP Version: 7.1

### Description:
Keep getting undefined index: email
![image](https://user-images.githubusercontent.com/4718721/30508643-bc4aa1e6-9ace-11e7-97be-8ccca0dc5f81.png)

using nodatabaseuserprovider
![image](https://user-images.githubusercontent.com/4718721/30508646-cd447fda-9ace-11e7-8fb1-6344efd4024f.png)

using samAccountName for LDAP
![image](https://user-images.githubusercontent.com/4718721/30508654-ddf7c0a8-9ace-11e7-9357-56bc9bf86665.png)

**Comment by stevebauman** [comment]
Thanks @entrique, you'll actually need to the the `eloquent` username attribute to match your login forms username field for the `NoDatabaseUserProvider`:

https://github.com/Adldap2/Adldap2-Laravel/blob/v3.0/src/Config/auth.php#L136-L150

I need to modify this so it uses only the `ldap` attribute, however this would cause breaking changes for developers so I'll need to have this patched in the future release.

**Comment by entrique** [comment]
Hi Steve,

I managed to use Auth::attempt to login on my forms now. 

However, all Auth::check() request resulted in a false boolean although users are logged in.

In Controller -> this will return true for Auth::check()
![image](https://user-images.githubusercontent.com/4718721/30527716-4033158e-9c5e-11e7-9800-02feff185939.png)

However in views, this will return false for Auth::check() for all Views
![image](https://user-images.githubusercontent.com/4718721/30527729-5ed092c8-9c5e-11e7-800e-b43b70274d8c.png)

**Comment by stevebauman** [comment]
Going to look into this, thanks!

**Comment by hugoabpeixoto** [comment]
I am getting the same error but I have not been able to solve it...

![image](https://user-images.githubusercontent.com/6783027/32565196-46311256-c4ae-11e7-998a-48debadcad3b.png)

What steps should I take to try and solve this...

I have just followed this steps:
https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/quick-start.md

And just got stuck there..My AD uses username insetad of email.

Cheers!

**Comment by hugoabpeixoto** [comment]
Sorry for the spam...I was able to go through this error..

But when I login it dows not provide any feedback...One refreshes and gives the same login page.. 

It doesn't create any user in the mysql database. I am using 

DatabaseUserProvider in my adldap_auth.php

**Comment by iraklisg** [comment]
@stevebauman I am getting exactly the same error as described in 
https://github.com/Adldap2/Adldap2-Laravel/issues/387#issuecomment-342902467 using L5.5. I too followed the steps provided in quick-start guide but I'm stack with the 
> ErrorException thrown with message "Undefined index: email"
@hugoabpeixoto did you have any progress on this?

**Comment by stevebauman** [comment]
Hi @hugoabpeixoto & @iraklisg,

The undefined index issue is due to passing in the users credentials with an incorrect username key that you've defined in your `adldap_auth.php` file.

For example, if I'm using usernames instead of email, but I don't modify anything and perform the following:

```php
// Notice the username key here.
$credentials = $request->only('username', 'password');

if (Auth::attempt($credentials)) {
    // Authenticated.
}
```
But in my `adldap_auth.php` file I have:

```php
'usernames' => [

     'eloquent' => 'email',

],
```

Then you will get `Undefined index 'email'`, since the Adldap auth driver is trying to retrieve the username from the given credentials.

Notice these lines here in the resolver:

https://github.com/Adldap2/Adldap2-Laravel/blob/b640e28420f10951e946a388b5ad001dab6a6b92/src/Resolvers/UserResolver.php#L70-L74

This is what generates the exception since it will try to retrieve the username from the given credentials array, but this key does not exist.

I'll fix this and add an exception with a reminder to configure this since there's continuously a lot of confusion about this.

**Comment by entrique** [comment]
I got it working by using:

if (Adldap::auth()->attempt(Input::get('username'), Input::get('password'))) instead of Auth::check()
