### ISSUE TITLE
Globally Unique Keys?

### ISSUE THREAD

**Issue by benyanke** [Adldap2/Adldap2-Laravel#396]
I'm working on this in my application, but having one big issue: how do I reference users across tables? If things change on the AD site, the primary key of a user's row changes, making it useless to use the primary key for FK linking.

Have you come up with a solution for this yet?

**Comment by stevebauman** [comment]
Hi @benyanke,

This isn't a feature that's built into Adldap2-Laravel. I have never needed globally unique identifiers inside my application databases. I'm absolutely open to discussion and PR's for implementing this though.

For a solution, you would have to use the LDAP users Object GUID and store it in a field in your database.

Though I wouldn't use the Object GUID as their FK, I would just use it for locating their user account to authenticate them with your application.

However this opens a can of worms, as what would happen if you have a user authenticating with their username / email, and there is already a user who exists in LDAP with the same username / email?

You would somehow need to identify your users upon login through something unique in your database, and to my knowledge, I'm not sure what a user could easily supply that would be globally unique besides their GUID (which is the only attribute in AD meant to be globally unique).

What are you expecting to change on your AD? I wouldn't expect the domain name or UPN suffix to change since that would be a disaster in an actual enterprise environment (would have to rejoin all computers to your domain and break tons of other things).

**Comment by benyanke** [comment]
How do you do it on your installations? I assume you have to store some sort of user information in other tables, then FK link back to the user table. What do you use as your FK?

You are right that GUID could work, but it's rather clunky and requires changes all up and down the auth stack, so I'm hoping to avoid it if at all possible. 

> What are you expecting to change on your AD?

I was going to use username, but that can sometimes change with marriages, etc.

**Comment by stevebauman** [comment]
> How do you do it on your installations? I assume you have to store some sort of user information in other tables, then FK link back to the user table. What do you use as your FK?

I use the regular users ID that's auto assigned when a user is imported. In my environment I don't need to worry about switching domains so it's not something I've invested time in implementing (though it would be a great feature to have).

> I was going to use username, but that can sometimes change with marriages, etc.

I've ran into this before, but in this case I usually just change the users username to match before they are allowed to login.

> this table would never be flushed (unlike the users table, perhaps), so that once a guid is linked to a user id, it can never be changed.

I like this idea, though wouldn't we run into the same issue locating user accounts upon login?

The user needs to provide something unique at the login form level. Using your solution, how would we locate the same account that has had their username changed?

Are you thinking the following flow:

1. User enters username in the login form
2. LDAP is queried for a user equal to the entered username
3. The GUID is retrieved and queried for in the local database to see if a user exists already with that GUID?

**Comment by benyanke** [comment]
I'm not really worried about switching domains, it's more about if I change the scope (currently, not all users can login). I've experienced in development where in some edge cases, a reimport can change things.

Really, what I'm just trying to find a way to hopefully implement it in a way where the data integrity is guaranteed (using the GUIDs, really). I'm sure it *could* work ok in production, but given the scale of our app I'm working on, I'm a bit worried about not having an accidental change of user ID.

Yes, that's the new algorithm I'm proposing. It would also allow local logins if LDAP is down, for users with logins stored in the DB from a previous login, by simply querying the user table as is usual.

**Comment by benyanke** [comment]
I'm going to close this issue - it turns out using GUID as the primary key was much easier than I thought. It's also by-far the safest way to do what I need.

Here's the steps, for anyone who wishes to follow:

1) Remove the ID from the user table database migration, and add the following in it's place:
```php
$table->uuid('guid')->unique();
              $table->primary('guid');
```
2) Add `protected $primaryKey = 'guid'` to the user model
3) Add a Guid SET attribute if need be, to ensure proper storage format from AD:
```php
     public function setGuidAttribute($value)
     {
         $this->attributes['guid'] = bin2hex($value);
     }
```

**Comment by victorlap** [comment]
One question, why would you want to rebuild your users table. I can't think of a reason for that..

**Comment by benyanke** [comment]
Changes of names/emails/other attributes on the AD side, for one

**Comment by benyanke** [comment]
Not to mention, if this is supposed to be an extension of AD, it's simply not safe from a data integrity standpoint to use a made-up key when a unique one is already available in AD
