### ISSUE TITLE
Can import and search users but can't login

### ISSUE THREAD

**Issue by Babrakov** [Adldap2/Adldap2-Laravel#398]
- Laravel Version: 5.5
- Adldap2-Laravel Version: 3.0
- PHP Version: 7.0

### Description:
When I try to login with login form there is "These credentials do not match our records." appears
Meanwhile if I insert into route.php `Adldap::search()->all()` or `dd(Adldap::search()->users()->find('myUserName'))` it's work perfect: I receive all records.
What can I do?

### Steps To Reproduce:
Install and config adldap by https://github.com/Adldap2/Adldap2/issues/188#issuecomment-185719456

[adldap.php.txt](https://github.com/Adldap2/Adldap2-Laravel/files/1349331/adldap.php.txt)
[adldap_auth.php.txt](https://github.com/Adldap2/Adldap2-Laravel/files/1349329/adldap_auth.php.txt)
[auth.php.txt](https://github.com/Adldap2/Adldap2-Laravel/files/1349330/auth.php.txt)

**Comment by stevebauman** [comment]
Hi @Babrakov,

Is the user you're trying to login as located inside your OU named `testDept` that's set in your `base_dn`?

**Comment by Babrakov** [comment]
Hi! Yes, user `admin` is in `testDept`. Here is screenshot from domain controller:
![image](https://user-images.githubusercontent.com/19371524/31111908-67dff7ca-a819-11e7-959d-51f604fcb58a.png)

**Comment by stevebauman** [comment]
Hi @Babrakov,

I know what's going on. You're using the `userprincipalname` to authenticate, but adding an `account_suffix` that would equal your user principal name.

For example, since you've set your `account_suffix` to `@forest.com`, when you authenticate and use the `userprincipalname`, the username you're trying to authenticate with is `admin@forest.com@forest.com`.

All you should need to do is change your `ldap` username to `samaccountname`.

`Auth::attempt()` should work after that.

Let me know!

**Comment by Babrakov** [comment]
Hi @stevebauman, you're rigth! It's all working now!
Thank you for [adldap ](https://github.com/Adldap2/Adldap2-Laravel) And many thanks to you for your helping.

**Comment by stevebauman** [comment]
Awesome, no problem at all! :)

**Comment by legreco** [comment]
I have the same problem, but in my case i must use userprincipalname to authenticate because in my organisation the userprincipalname is not samaccountname@organisation.org
Exemple
userprincipalname : jeanrobert@organisation.org
samaccountname: jrobert@organisation.org

In my application people used to log in with samaccountname but i had to change it to userprincipalname because people rarely remember their samaccountname.
But i cant get it to work this way. I dont know why. 

Can you help me with that?
