### ISSUE TITLE
BindException displaying password AD

### ISSUE THREAD

**Issue by eufernandodias** [Adldap2/Adldap2-Laravel#424]
- Laravel Version: 5.4.36
- Adldap2-Laravel Version: 3.0
- PHP Version: 7.0.22

### Description:
BindException displaying password when occurs connection error with Active Directory

### Steps To Reproduce:
Config wrong password to admin_password in adldap.php config

PS. Sorry for my English

![screenshot-127 0 0 1-8000-2017-11-18-12-59-53-565](https://user-images.githubusercontent.com/4853219/32981730-96758a1c-cc60-11e7-9a18-3dfafadde9c1.png)

**Comment by stevebauman** [comment]
This is expected, its just a stack trace of BindException because your admin password is incorrect. 

In production environments you would catch this exception and / or hide all exceptions when you set your applications environment to production.

Is there some other issue with this that I'm not seeing?

**Comment by eufernandodias** [comment]
@stevebauman 

Tks for your fast answer.

Just it. You are correct.

Tks
