### ISSUE TITLE
Adldap::search()->get() does not return any results

### ISSUE THREAD

**Issue by ngrippa** [Adldap2/Adldap2-Laravel#426]
Hey, i have trouble finding any users at my ldap.
`Adldap::search()->get()` fails and returns an empty array. Can somebody explain me why this happens? I can contact the LDAP server but don't get any users (an empty array instead). Even `Adldap::search()->setDn('existing dn')->get();` fails, with the dn directly copied from LDAP Browser (`uid=username,cn=xxx,ou=yyy,l=zzz,dc=de,o=mycorp`). Are there any .env variables applied to this syntax, which may can be wrong?

Note that I am able to bind to the server (if I change the admins user name or password I get an error message, so I am definitely connecting to the server!)
Do you have an idea what I am doing wrong?

**Comment by stevebauman** [comment]
Hi @ngrippa,

This is likely due to an invalid base DN, or other configuration settings.

Have you changed your schema in the configuration for OpenLDAP instead of ActiveDirectory?

The ActiveDirectory schema is configured by default and **will not** work with OpenLDAP.

Also ensure your base DN is correct in your configuration file (`config/adldap.php`).

Your search query is also incorrect, as you're setting the distinguished name to a user account, which will return null unless you specify that you want to **read** from the set distinguished name.

To locate an exact record, you can either use the built in method `findByDn()` or manually.

**Using built in method**:

```php
$dn = 'uid=username,cn=xxx,ou=yyy,l=zzz,dc=de,o=mycorp';

$user = Adldap::search()->findByDn($dn);
```

**Manually**:

```php
$dn = 'uid=username,cn=xxx,ou=yyy,l=zzz,dc=de,o=mycorp';

$user = Adldap::search()->read()->in($dn)->whereHas('objectclass')->first();
```

If you still encounter issues, please comment back and I will re-open this, thanks!
