### ISSUE TITLE
Advice - Using LDAP SSL w/ Valet during Development

### ISSUE THREAD

**Issue by mgrimard** [Adldap2/Adldap2-Laravel#430]
- Laravel Version: 5.5
- Adldap2-Laravel Version: 3.0
- PHP Version: 7.2

### Description:
Hopefully this is an alright question to ask here, is this something that is possible? Any tips for setting it up to use my ADLDAP certificate so that it allows the SSL connection?

### Steps To Reproduce:
Enable SSL while using Valet to host your site during development.

**Comment by stevebauman** [comment]
Hi @mgrimard, sorry for the overdue reply here.

Unfortunately I have barely any knowledge with using Laravel Valet as I run in a Windows only environment.

However, SSL or TLS needs to first be enabled on your LDAP server, and then you can utilize it. You may need to create some configuration files and add your certificate to Laravel Valet's PHP server, but I have no knowledge of doing so.

This may help you:

http://www.openldap.org/faq/data/cache/185.html

Once you've setup SSL / TLS on your AD server and configure Laravel Valet's PHP server, you can turn it on simply by setting `use_ssl` or `use_tls` to `true` in your Adldap2 configuration (you cannot turn both on though).

Since this issue was created last year, I'll close this out as it hasn't received any help from the community. I would suggest asking on StackOverflow or a PHP forum to help you out with this.
