### ISSUE TITLE
Cannot Get Authentication to work.

### ISSUE THREAD

**Issue by faaazma** [Adldap2/Adldap2-Laravel#45]
Hi..

Need help.. I been trying for hours to get the auth working however failed. I got sample code which i tested working using ldap library but i did not manage to the auth working. The code that working is

$host = 'ibnuhajar.iium.edu.my';
		$port = 389;
		$basedn = 'cn=Users, dc=iiu, dc=edu, dc=my';

		$auth = '0';

		$PHP_AUTH_USER = 'faaazma';
		$PHP_AUTH_PW = 'wildfire';

		if ($PHP_AUTH_USER != "" && $PHP_AUTH_PW != "") {
	    	$ds=ldap_connect($host,$port);
	    	$r = ldap_search( $ds, $basedn, 'uid=' . $PHP_AUTH_USER);
	    	if ($r) {
	        	$result = ldap_get_entries( $ds, $r);
	        	//dd($PHP_AUTH_USER,$PHP_AUTH_PW,$result);
	        	if (array_key_exists(0,$result)) {
	            	$bind_with_pwd = ldap_bind( $ds, $result[0]['dn'], $PHP_AUTH_PW);
	            	if ($bind_with_pwd) {
	                	//return $result[0];
	                	$auth = '1';
	            	} else {

	                	$auth = '3';
	            	}
	        	}
	    	} else {

	        	$auth = '2';
	    	}
		}

What config should be in my config/adldap.php and adldap_auth.php to make it work.

I manage to get and entry working as in

$ldapuser =      Adldap::search()->where('cn', '=', 'faaazma')->first(); which result an ENTRY records.

but failed for  

$user = Adldap::users()->find('faaazma'); // it return false from dd

Attached are my config/adldap.php and adldap_auth.php and login.blade.php.

Please assist.

[adldap.php.txt](https://github.com/Adldap2/Adldap2-Laravel/files/107776/adldap.php.txt)
[adldap_auth.php.txt](https://github.com/Adldap2/Adldap2-Laravel/files/107777/adldap_auth.php.txt)
[login.blade.php.txt](https://github.com/Adldap2/Adldap2-Laravel/files/107779/login.blade.php.txt)

**Comment by stevebauman** [comment]
You shouldn't be binding manually. Adldap binds to your server automatically using your configuration.

You also won't find yourself using `Adldap::users()->find('faaazma');`, since `faaazma` is actually located in the `cn` attribute like you've shown above. The `users()->find()` method locates users by their [`samAccountName` attribute](https://github.com/Adldap2/Adldap2/blob/v5.2/src/Classes/Users.php#L20).

Have you followed the installation and usage documentation for the Auth driver?

https://github.com/Adldap2/Adldap2-Laravel#auth-driver

You need to utilize laravel's stock `AuthController.php` located in `app/Http/Controllers`;

**Comment by stevebauman** [comment]
Closing until more information is provided.
