### ISSUE TITLE
Import command not considering --connection option

### ISSUE THREAD

**Issue by EcoFreak** [Adldap2/Adldap2-Laravel#451]
- Laravel Version: 5.2
- Adldap2-Laravel Version: 3.0
- PHP Version: 7.0.22
- LDAP Type: Active Directory or OpenLDAP

### Description:

When using the adldap:import command, the --connection option is not being used.
The import is always made with regard to the default connection.

Thanks in advance!

### Steps To Reproduce:

Use the command with an alternate connection

php artisan adldap:import <some_user> --connection <connection_name>

**Comment by stevebauman** [comment]
Hi @EcoFreak, this option had issues when it was first implemented. It was later removed due to the difficulty of implementing it in the current code base without BC breaks.

Unfortunately it slipped my mind to remove it from the documentation ☹️.

If you can provide a PR or implementation to put this back in it would be appreciated :smile:
