### ISSUE TITLE
Database password not being reset each time a LDAP login occurs

### ISSUE THREAD

**Issue by rbmcgowan** [Adldap2/Adldap2-Laravel#506]
- Laravel Version: 5.6
- Adldap2-Laravel Version: latest / f2b8b4a  
- PHP Version: 7.1
- LDAP Type: OpenLDAP

Document says:

```
|--------------------------------------------------------------------------
| Password Sync
|--------------------------------------------------------------------------
...
| If this option is disabled, the local database account is applied a
| random 16 character hashed password upon every login, and will
| lose access to this account upon loss of LDAP connectivity.
```

This doesn't seem to be happening, I can log in with an old password stored in the users table whenever LDAP isn't available.

This creates an issue since when a user is disabled in LDAP they can continue to login using an old password.

```
 'sync' => env('ADLDAP_PASSWORD_SYNC', false),
```

### Steps To Reproduce:

- Disable LDAP
- Reset password in Laravel
- Enable LDAP
- Login with LDAP account & password
- Disable LDAP 
- Login with original users table password. This shouldn't be possible if the local database password was updated  with a random value every time LDAP logs you in.

**Comment by stevebauman** [comment]
Hi @rbmcgowan, this was actually labelled as an issue from other users due to running a SQL update on every single user login:

https://github.com/Adldap2/Adldap2-Laravel/pull/449

This was later included in the `v4.0` release here:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Commands/SyncPassword.php#L84-L93

Do you have a solution that would satisfy both needs?

We do have the users model while syncing passwords. I was thinking maybe we can do a timestamp compare to the last update the user model has had and update the password if it's been longer than a day since it has been updated?

However, that would rely on the users model not changing for a day for this to occur which could give some strange side effects.

**Comment by rbmcgowan** [comment]
I see, maybe it could be an option ? one extra database update on a login isn't going to upset to many environments.

Any suggestions on how I could best reactive this?

I have also run into another problem, I need to ensure that company users (who would all have a particular email domain suffix @xxxxxxxxx.com) can ONLY login via LDAP. Other users (members of the public) can log in via local db authentication. Any thoughts on where to best implement that?

thanks for your time and for this great ldap tool !

**Comment by stevebauman** [comment]
Hi @rbmcgowan,

You can actually update their password yourself upon every LDAP login using an attribute handler:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth.md#attribute-handlers

```php
namespace App\Handlers;

use App\User as EloquentUser;
use Adldap\Models\User as LdapUser;

class LdapAttributeHandler
{
    /**
     * Synchronizes ldap attributes to the specified model.
     *
     * @param LdapUser     $ldapUser
     * @param EloquentUser $eloquentUser
     *
     * @return void
     */
    public function handle(LdapUser $ldapUser, EloquentUser $eloquentUser)
    {
        // Set a new random hashed password upon login.
        $eloquentUser->password = bcrypt(str_random(16));
    }
}
```

> I have also run into another problem, I need to ensure that company users (who would all have a particular email domain suffix @xxxxxxxxx.com) can ONLY login via LDAP. Other users (members of the public) can log in via local db authentication. Any thoughts on where to best implement that?

You may be able to use the `login_fallback` configuration option, however things to be aware of:

If, in the following scenario, your application:

- Loses AD connectivity OR your user is deleted in AD
- You have `password_sync` on

Then this user would be allowed to authenticate into your web application with the `login_fallback` option, as the user couldn't be located and the password that they last used would be still valid in your local application database (password sync being on).

You'll likely need to implement this yourself. I would turn off `login_fallback` as well as `password_sync`, then during the login request, manually set your auth driver at runtime before `Auth::attempt()` is called inside your `LoginController.php`:

```php
public function login($request)
{
    $suffix = '@mydomain.com';

    if (str_contains($request->email, $suffix)) {
        // This user belongs to LDAP, we'll change our driver here.
        Config::set('providers.users.driver', 'adldap');
    } else {
        Config::set('providers.users.driver', 'eloquent');
    }

    // Auth::attempt()
}
```

I'm going to close this for now since the described issue can be resolved easily with an attribute handler.

However, I really appreciate you taking the time to let me know about this :)

**Comment by rbmcgowan** [comment]
Thanks, I appreciate your time, responses and suggestions, which I will look into now. Again, great tool, thanks for making it available.

**Comment by rbmcgowan** [comment]
I'm trying to get the company attribute from ldap via ...

$userldap = Adldap::search()->where('mail', '=', auth::user()->email)->get();
$company = $userldap->company;

But all I get is "Property [company] does not exist on this collection instance." however when I dd($userldap) I can see the company attribute ok.  I guess I am misunderstanding how to extract LDAP attributes. Any pointers?  sorry for hassling you with my lack of knowledge.
