### ISSUE TITLE
Unable to login with username

### ISSUE THREAD

**Issue by AndreaRunner** [Adldap2/Adldap2-Laravel#592]
- Laravel Version: 5.7
- Adldap2-Laravel Version: 4.0
- PHP Version: 7.2
- LDAP Type: ActiveDirectory

### Description:
I've a fresh laravel installation to try this package.
I've installed : 
  "adldap2/adldap2": "^8.0",
  "adldap2/adldap2-laravel": "^4.0",
and try to configure, but **I'm lost in documentation** to login with username.
I don't understand the correct steps to work.
I've ths error:
![image](https://user-images.githubusercontent.com/38216051/46152290-01144a00-c271-11e8-8699-80283d95cec1.png)
If you want i make a new laravel installation ... no problem ... this is a test 
Tell me what to check, help me please ... 
thanks in advance!

**Comment by 2PeterSteiner** [comment]
I have the same problem.
I'm looking for a tutorial to login with active directory and laravel. I've spend a lot a time and I'm stuck her.

Is there any example to config the laravel authentication with adlap2 against windows ad?

Best regards
Hans-Peter

**Comment by jeremiahsherrill** [comment]
This would be fantastic, I am stuck here as well.

**Comment by stevebauman** [comment]
@2PeterSteiner all examples and tutorials on the documentation site are all based on ActiveDirectory.

This issue is already described in the documentation:

https://adldap2.github.io/Adldap2-Laravel/#/auth/setup?id=ldap

I've also described and walked through this issue multiple times on several issues here.

The `ldap_auth.usersnames` array is what causes this. You need to have your HTML **input field name** the same as your `ldap_auth.usernames.eloquent` **value**. **UNLESS** you are using the `NoDatabaseUserProvider`, then the `ldap_auth.usernames.ldap.discover` **must match** your HTML input field name.

You can see this taking place in the `Resolver::byCredentials()` method:

https://github.com/Adldap2/Adldap2-Laravel/blob/9c4e0f04e64245f19de286842b0f062fa8350681/src/Resolvers/UserResolver.php#L61-L82

This option controls how Adldap2-Laravel knows what array key contains your users username when passed into Laravel's `Auth::attempt()` method in the `LoginController`.
