### ISSUE TITLE
Not getting custom sync_attributes

### ISSUE THREAD

**Issue by sachaw** [Adldap2/Adldap2-Laravel#593]
- Laravel Version: 5.7
- Adldap2-Laravel Version: Latest
- PHP Version: 7.2
- LDAP Type: ActiveDirectory

### Description:
after defining other LDAP user properties under sync_attributes, value is not obtained and throws SQL exceltion:
`Column 'memberOf' cannot be null (SQL: update `users` set `memberOf` = , `updated_at`...`

### Steps To Reproduce:
create appropriate user table column
edit adldap_auth.php with the following

    'sync_attributes' => [

        'username' => 'samaccountname',

        'name' => 'cn',

        'memberOf' => 'memberOf',

    ],

**Comment by sachaw** [comment]
Found it was caused by typo, turns out all attributes are decapitalised, compared the the attribute in AD, may want to document this, as I'm sure someone else will have the same issue, or possibly add an exception for when the attribute does not exist.

**Comment by stevebauman** [comment]
Hi @sachaw,

Thanks for pointing this out! I'll be sure to add this into the docs.

This is done to prevent casing issues with different schemas using other LDAP distros.

I don't really want to add an exception for non-existing attributes, because devs can add this themselves inside [Attribute Handlers](https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth.md#attribute-handlers).

The attribute could also be `nullable` in their  SQL schema and they may want `null` values for non-existing attributes.

**Comment by sachaw** [comment]
Perfect, Thanks

**Comment by dany-micheal** [comment]
hi @stevebauman i have the same issue

**Comment by stevebauman** [comment]
Hi @dany-micheal, please create an issue with your details and I will assist you there.
