### ISSUE TITLE
Problem to filter from base DN

### ISSUE THREAD

**Issue by erotundo** [Adldap2/Adldap2-Laravel#594]
Adldap2 Version: 4.0
LDAP Type: OpenLDAP
PHP Version: 7.1
Laravel 5.5
Description:
Problem to search a user into all AD.

I have a AD with differents OU and i want to search one user using sAMAccountName into AD only using the root DN

Steps To Reproduce:
Example:

DN=test,DN=es

I have 4 OU

OU=1
OU=2
OU=3
OU=4

The user it's located into OU=4, but the library don't search into all OU to find the user

Regards

ER

**Comment by stevebauman** [comment]
Hi @erotundo,

Have you set your `base_dn` in your `adldap.php` file to `DN=test,DN=es`?

This package does not limit searches. As long as your `base_dn` is set correctly, every record that is a child of that base will be returned with search results.

You can easily test this via:

```php
use Adldap\Laravel\Facades\Adldap;

$users = Adldap::search()->in('DN=test,DN=es')->get();
```

Also, you've specified your LDAP type as OpenLDAP, but mention AD? Then you mention `sAMAccountName` as well, which you'd actually have to manually include into your OpenLDAP schema to use, since `sAMAccountName` is only available in ActiveDirectory by default.
