### ISSUE TITLE
Determine admin account prefix automatically

### ISSUE THREAD

**Issue by freescout-helpdesk** [Adldap2/Adldap2-Laravel#626]
- Laravel Version: 5.5
- Adldap2-Laravel Version: 4.0.10
- PHP Version: 7.1
- LDAP Type: ActiveDirectory / OpenLDAP / FreeIPA

### Description:

Is it possible to determine admin account prefix ( `cn=` or `uid=`) automatically when having just LDAP host and Base DN?

### Steps To Reproduce:

I need to be able to connect to any LDAP server without knowing it's type (ActiveDirectory / OpenLDAP / FreeIPA).

**Comment by stevebauman** [comment]
Hi @freescout-helpdesk,

You could determine its prefix by checking which schema is in use on the connection provider:

```php
use Adldap\Laravel\Facades\Adldap;

$schema = Adldap::getDefaultProvider()->getSchema();

// Check if the schema inherits or is ActiveDirectory
if (is_a($schema, Adldap\Schemas\ActiveDirectory)) {
    $prefix = 'cn=';
} else {
    $prefix = 'uid=';
}
```

The thing is though, you'll need the account suffix as well to be able to authenticate, which you won't be able to determine automatically because the account can be contained in any number of OUs.

For example: `cn=admin,ou=Adminstrators,ou=Users,dc=acme,dc=org`

It would only be somewhat possible using ActiveDirectory to determine a users username with just their base DN, as we could explode it (using `ldap_explode_dn()`) and assume their `userPrincipalName` suffix would align with their base DN, for example, if their base DN was `dc=acme,dc=org`, then their `userPrincipalName` suffix would likely be `@acme.org`, which you could then apply to their username as `jdoe@acme.org`.

Though in my opinion, I think it would be better off to trust users / developers to enter in the full username of the account they need to connect with, and simply fire bind request to validate that their credentials are correct before saving them.

I hope this was of some use to you, and If you'd like to have further discussion, just leave a comment and I'll re-open this.

**Comment by Albvadi** [comment]
This is my own solution for this: https://github.com/Adldap2/Adldap2-Laravel/issues/117#issuecomment-224550280

Maybe can help you...

**Comment by freescout-helpdesk** [comment]
Thanks. 

Adldap2-Laravel supports out of the box only 3 LDAP types: ActiveDirectory, OpenLDAP, FreeIPA? Right?

I'm exploring Active Directory server ldap.forumsys.com ([docs](https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/ )). It requires `admin_account_prefix` to be `cn=`. Does Active Directory servers always require `admin_account_prefix="cn="` and OpenLDAP server always require `admin_account_prefix="uid="`? Or it depends on each server's configuration?
