### ISSUE TITLE
Exception Undefined index: uid

### ISSUE THREAD

**Issue by afrizaislami** [Adldap2/Adldap2-Laravel#638]
- Laravel Version: 5.7
- Adldap2-Laravel Version: 5.0.2
- PHP Version: 7.1
- LDAP Type: Active Directory

### Description:
I'm trying to make an API for logging in by using adldap2-laravel. 
But I got this error ""message": "Undefined index: uid", "exception": "ErrorException"., however it connected well to my AD.  

### Steps To Reproduce:

```php
public function signin(Request $request)
    {
    	$credentials = $request->only('username', 'password');
    	$username = $credentials['username'];
        $password = $credentials['password'];
        
        try 
        {
        	Adldap::connect();
       }
    	catch (\Exception $e) 
    	{
			return response()->json(['error' => 'not connected to LDAP']);
       	}
    	if (Auth::attempt($credentials)) {
        	// Passed.
        		return response()->json(['message' => 'successfully logged in']);
        }
    	else{
    			return response()->json(['error' => 'username or password is wrong']);
    	}

    }
```

Thank you.

**Comment by stevebauman** [comment]
Hi @afrizaislami,

What provider are you using? The `DatabaseUserProvider` or the `NoDatabaseUserProvider`?

If you're using the `DatabaseUserProvider`, your username HTML input field name must match your configured `ldap_auth.usernames.eloquent` value here:

https://github.com/Adldap2/Adldap2-Laravel/blob/8d6a47feb490f0e3e090f5102728455caaed0371/src/Config/auth.php#L143

Otherwise, if you're using the `NoDatabaseUserProvider`, your username HTML input field name must match the `ldap_auth.usernames.ldap.discover` value here:

https://github.com/Adldap2/Adldap2-Laravel/blob/8d6a47feb490f0e3e090f5102728455caaed0371/src/Config/auth.php#L123

Give that a shot and let me know if you still encounter issues and I will re-open this.
