### ISSUE TITLE
Port value on ssl

### ISSUE THREAD

**Issue by bmarsilio** [Adldap2/Adldap2-Laravel#64]
If I change the attribute 'use_ssl' to 'true', the connection method should change the connection port from 389 to 636

**Comment by stevebauman** [comment]
If you set the port manually to `null` inside your configuration, the default SSL will be used **if SSL is enabled in your configuration**.

This would lead to unintended results if the user configures a different port on their AD server for SSL and their configured port is being changed due to having SSL on.

**Comment by stevebauman** [comment]
Nope you're right, this change doesn't occur when it's set to null. Will fix shortly.

**Comment by bmarsilio** [comment]
Ok.
Another question. Could you show me some documention about how I prepare my application to use the create users feature? I followed the https://github.com/Adldap2/Adldap2/blob/v5.2/docs/models/USER.md doc but didn't work well

Thanks

**Comment by stevebauman** [comment]
Fixed https://github.com/Adldap2/Adldap2/blob/v5.2/src/Connections/Configuration.php#L140
