### ISSUE TITLE
Resolver::byCredentials returns an instance of Entry

### ISSUE THREAD

**Issue by travisobregon** [Adldap2/Adldap2-Laravel#666]
- Laravel Version: 5.7
- Adldap2-Laravel Version: 5.1
- PHP Version: 7.2
- LDAP Type: OpenLDAP

### Description:
In the retrieveByCredentials method in the DatabaseUserProvider, the following line sets $user to an instance of Entry: `$user = Resolver::byCredentials($credentials);`

Is this incorrect because the condition that follows expects an instance of User?

**Comment by stevebauman** [comment]
Hi @travisobregon,

If an `Entry` is returned, that means that the search factory couldn't map the object class of the returned LDAP object to any other model instance, thus a basic `Entry` model will be returned.

Did you update your `schema` configuration option to the `OpenLDAP` schema?

**Comment by travisobregon** [comment]
Sorry, I understand now.

The objectClass on the test ldap server I have is equal to 'user', rather than 'inetorgperson'. So the line below doesn't contain a mapping for me:
https://github.com/Adldap2/Adldap2/blob/ebf40c48092b51ef6f7390d086f6ad848ef318b6/src/Query/Processor.php#L120

I had previously hardcoded 'user' in the line below to get the query to work, so that is why I got as far as returning an instance of Entry
https://github.com/Adldap2/Adldap2/blob/ebf40c48092b51ef6f7390d086f6ad848ef318b6/src/Query/Factory.php#L126

I am going to try update the objectClass on my test server, which should fix my issue.

Thanks for your work . Sorry for wasting your time.

**Comment by stevebauman** [comment]
Hi @travisobregon, no worries at all! No time wasted, I appreciate you creating an issue and asking for clarification.

In your case you can extend the current built-in `OpenLDAP` schema with your own and override the `objectClassPerson()` and `objectClassUser()` methods with `user` instead of `inetorgperson`:

https://github.com/Adldap2/Adldap2/blob/ebf40c48092b51ef6f7390d086f6ad848ef318b6/src/Schemas/OpenLDAP.php#L71-L85

```php
namespace App\Schemas;

use Adldap\Schemas\OpenLDAP as BaseSchema;

class OpenLDAP extends BaseShema
{
    /**
     * {@inheritdoc}
     */
    public function objectClassPerson()
    {
        return 'user';
    }
    /**
     * {@inheritdoc}
     */
    public function objectClassUser()
    {
        return 'user';
    }
}
```

This will allow the search factory to recognize the object class and return the proper model instance.

If you need help or have more questions give me a shout, thanks!
