### ISSUE TITLE
Binding as user

### ISSUE THREAD

**Issue by travisobregon** [Adldap2/Adldap2-Laravel#672]
- Laravel Version: 5.7
- Adldap2-Laravel Version: 5.1
- PHP Version: 7.2
- LDAP Type: ActiveDirectory / OpenLDAP / FreeIPA

### Description:
Hi, 

I just had a question about binding as a user to the LDAP server. Is there a reason why there is no config option to set this to `true`?

https://github.com/Adldap2/Adldap2-Laravel/blob/6b6a247f663639ff344718542023ede340efba3b/src/Resolvers/UserResolver.php#L118

I would be more than happy to create a PR if you think it would be a good idea to have. If not, do you have a recommendation on how to best get around this?

Thanks.

**Comment by stevebauman** [comment]
Hi @travisobregon,

There's no config option because any subsequent HTTP requests after the initial binding will still require a configured username and password - so I felt it was somewhat pointless to add as an option.

For example, after a user logs in and they are bound to the LDAP server, on the next HTTP request the LDAP connection will not be re-bound under that user. It will still require a configured username and password to bind on any further requests because we won't have their username and password stored anywhere.

I'm not against accepting your PR though if you have a valid use-case that I'm not seeing? Are you able to explain what benefit we would get offering this as a config option?

Thanks! :smile:

**Comment by travisobregon** [comment]
Okay, I didn't realise that the LDAP connection will not be re-bound.

The reason I was hoping this would work is because the password of the account I was using to connect expires every few weeks. Rather than having to remember to keep updating the password and causing unnecessary downtime, I was hoping binding as the user would work.

**Comment by stevebauman** [comment]
Yea unfortunately it won’t work on further requests after the initial auth attempt.

Are you able to maybe setup an AD service account that you only expire every couple months? I currently do this in my environment.
