### ISSUE TITLE
General error: 1364 Field 'username' doesn't have a default value (username auth)

### ISSUE THREAD

**Issue by jeremiahsherrill** [Adldap2/Adldap2-Laravel#729]
- Laravel Version: 5.8
- Adldap2-Laravel Version: 6.0
- PHP Version: 7.3
- LDAP Type: ActiveDirectory

### Description:
`Illuminate/Database/QueryException with message 'SQLSTATE[HY000]: General error: 1364 Field 'username' doesn't have a default value (SQL: insert into `users` (`objectguid`, `email`, `name`, `password`, `updated_at`, `created_at`) values (234234234234234, email@email.local, John Doe, $2y$10avmeB3suzeWklDD.J99lYBevKVqCK4CMJaBNdxDsnSKoP4s9qyhaeO, 2019-05-07 17:33:45, 2019-05-07 17:33:45))'`

I am trying to use the username option, but the sql is still submitting as email.   Looking through quick start, thought I have covered everything, but not sure.

**Comment by stevebauman** [comment]
Hi @jeremiahsherrill,

Did you change your `sync_attributes` config option inside your `ldap_auth.php` file to the following:

```php
'sync_attributes' => [
    'username' => 'samaccountname',
    'name' => 'cn',
],
```

**Comment by jeremiahsherrill** [comment]
yes, that wasn't it.   I was able to get it working

**Comment by stevebauman** [comment]
Glad to hear! Thanks for the quick response.

**Comment by asadsajjad** [comment]
> ldap_auth.php

where to find this file ?

**Comment by jeremiahsherrill** [comment]
php artisan vendor:publish --provider="Adldap\Laravel\AdldapAuthServiceProvider"

**Comment by KhoshnevisRad** [comment]
dear sir
At first go to "config\database.php" and then change 'strict' => true to false value.
good luck

**Comment by AsifMian** [comment]
### in my case  'strict' => true to false value did not worked ....

Illuminate\Database\QueryException
SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value (SQL: insert into `signup_forlaunch` (`name`, `brand`, `Email`, `updated_at`, `created_at`) values (fsdf, sdf, ali@vomoto.com, 2020-09-16 07:34:16, 2020-09-16 07:34:16))

**solution:**
it was due to database export error from local to online.
Menas in that table it was not enabling auto_increment so i manually enabled the auto_increment for the id field and it resolved the issue
