### ISSUE TITLE
When using command " import " ,  is this only check user count?? 

### ISSUE THREAD

**Issue by inyoungk** [Adldap2/Adldap2-Laravel#779]
- Laravel Version: 5.7
- Adldap2-Laravel Version: 6.x
- PHP Version: 7.1
- LDAP Type: ActiveDirectory 

In terminal, I typed "php artisan adldap:import"
just like https://adldap2.github.io/Adldap2-Laravel/#/auth/importing?id=scheduling-the-command

but that is only check user count.
Even if the credential was wrong, that throws ""There were no users found to import." Runtime exception,

Is there a way i can check what kind of error is?

If I have to develop, how can i do this??

**Comment by stevebauman** [comment]
Hi there @inyoungk,

You can check your `storage/logs` directory if there are issues during the import, or the credentials are incorrect. LDAP errors are reported there.

Otherwise, if you would like to programmatically retrieve the last error encountered while trying to import users, you should be able to do this in your schedule:

```php
/**
 * Define the application's command schedule.
 *
 * @param \Illuminate\Console\Scheduling\Schedule $schedule
 *
 * @return void
 */
protected function schedule(Schedule $schedule)
{
    // Import LDAP users hourly.
    $schedule->command('adldap:import', [
        '--no-interaction',
        '--restore',
        '--delete',
        '--filter' => '(objectclass=user)',
    ])->hourly();

    $lastError = Adldap::getConnection()->getLastError();
}
```

Let me know if you run into issues and I'll re-open this, thanks!
