### ISSUE TITLE
Import and authenticate only members of nested group

### ISSUE THREAD

**Issue by Sebi94nbg** [Adldap2/Adldap2-Laravel#817]
- Laravel Version: 6.5
- Adldap2-Laravel Version: 6.0.8
- PHP Version: 7.2.x
- LDAP Type: ActiveDirectory

### Description:

I have a group called `CN=App_Intranet,OU=Applications,OU=_Groups,DC=example,DC=com`, which is member of the default Active Directory group `Domain Users`.

So all `Domain Users` are automatically member of the group `App_Intranet`.

I would like to update the command `php artisan adldap:import --restore --delete` to import only users, which are member of this group.

Same for the authentication: I've created a rule and would like to only allow logins for users, which are member of this group:

```
<?php

namespace App\Rules;

use Adldap\Laravel\Validation\Rules\Rule;

class OnlyMemberOfRequiredGroupDn extends Rule
{
    /**
     * Determines if the user is allowed to authenticate.
     *
     * @return bool
     */
    public function isValid()
    {
        return $this->user->inGroup('CN=App_Intranet,OU=Applications,OU=_Groups,DC=example,DC=com');
    }
}
```

The problem is, that it always can not find any user - the import for example says always 0 users found.

`Auth::User()->ldap->getGroups()` does also never display the nested groups.

Related issue: #709

**Comment by stevebauman** [comment]
Hi @Sebi94nbg,

Since this is a nested group, you'll need to pass in `true` into the second parameter to retrieve a recursive list of groups:

```
public function isValid()
{
    $dn = 'CN=App_Intranet,OU=Applications,OU=_Groups,DC=example,DC=com';

    return $this->user->inGroup($dn, $recursive = true);
}
```

That should resolve your issue!

**Comment by Sebi94nbg** [comment]
I've tried that, but even with this second parameter on `true` it did not change any result. :(

**Comment by stevebauman** [comment]
I would perform some debugging. Grab a user somewhere in your app and start dumping data.

```php
$user = Adldap::search()->users()->findOrFail('jdoe');

// Or use the users DN to locate them:
$user = Adldap::search()->users()->findByDnOrFail('cn=John Doe,dc=acme,dc=org');

// See if a group instance is returned:
$group = $user->getPrimaryGroup();
dd($group);

// If so, see if the primary group is a member of the group your looking for:
dd($group->getGroups());
```

**Comment by stevebauman** [comment]
Also, I'm assuming your users have their **Primary Group** set to **Domain Users** in your AD instance?

**Comment by Sebi94nbg** [comment]
Yes, the primary group is Domain Users. This confirms `getPrimaryGroup()` as well: `CN=Domain Users,CN=Users,DC=example,DC=com `

And
```php
foreach ($user->getGroups() as $group) {
    $this->info(json_encode($group->distinguishedname));
}
```
also contains the `Domain Users` group:
```
["CN=Domain Users,CN=Users,DC=example,DC=com"]
```

**Comment by Sebi94nbg** [comment]
Ah, I found the issue.

I'm just not sure, if it's a logic failure from my side or an issue of this package.

Following scenario:

- OU `CN=Users,DC=example,DC=com` contains all users within sub OUs (eg. `CN=john.doe,OU=Berlin,OU=Users,DC=example,DC=com`)
- Group `Domain Users` is located in `CN=Domain Users,CN=Users,DC=example,DC=com`
- Base DN in Adldap2 is configured to `OU=Users,DC=example,DC=com` since I only want to get users from the OU mentioned in point 1

Using this Base DN, the authentication is failing and the `Domain Users` group is missing in the `getGroups()` result.

When I change the Base DN to `DC=example,DC=com`, everything is working fine. BUT then I get too much objects, which slows down everything AND I get users, which I don't want.

**Comment by Sebi94nbg** [comment]
@stevebauman any idea?

**Comment by stevebauman** [comment]
Hey @Sebi94nbg, apologies for the late response.

This isn't actually a bug with Adldap2, but how searching an LDAP directory works. Since you've set your `base_dn` to an Organizational Unit, you will only retrieve results **inside** of that OU, throughout all of your LDAP search requests.

It's best practice to have the lowest level leaf set as your `base_dn`, so you don't run into these issues of searching outside of the scope. Unless of course you're certain that you won't be needing or searching outside the scope of the base you've set.

> When I change the Base DN to DC=example,DC=com, everything is working fine. BUT then I get too much objects, which slows down everything AND I get users, which I don't want.

There's two options you can do here:

1. Create your own `UserResolver` and extend from the current one. Then, return a query that is scoped inside the OU you've shown above. Adldap2 will use your `base_dn` set in your configuration for all searches, so when your `inGroup()` call is executed on a user, the correct results will be returned. Here's an example:

Built in resolver:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Resolvers/UserResolver.php

Custom resolver:

```php
namespace App\Ldap;

use Adldap\Query\Builder;
use Adldap\Laravel\Resolvers\UserResolver as BaseResolver;

class UserResolver extends BaseResolver
{
    public function query() : Builder
    {
        return parent::query()->in('OU=Users,DC=example,DC=com');
    }
}
```

Swap the resolver instance with your own (in your `AppServiceProvider`):

```php
use App\Ldap\UserResolver;
use Adldap\Laravel\Facades\Resolver;

public function boot()
{
    $customResolver = app(UserResolver::class);

    Resolver::swap($customResolver);
}
```

2. Create a custom scope that performs the same task:

https://adldap2.github.io/Adldap2-Laravel/#/auth/setup?id=scopes

```php
namespace App\Scopes;

use Adldap\Query\Builder;
use Adldap\Laravel\Scopes\ScopeInterface;

class UserScope implements ScopeInterface
{
    public function apply(Builder $query)
    {
        $query->in('OU=Users,DC=example,DC=com');
    }
}
```

Add it into your `ldap_auth.php` configuration file:

```php
'scopes' => [
    \App\Ldap\UserScope::class,
],
```

Then, flush your cache (in case you're caching your configuration files):

```bash
php artisan config:clear
```

I hope this helps! Give one of the options a try and let me know if the speed increases significantly, or if it's still encountering issues.

**Comment by Sebi94nbg** [comment]
Wow. Awesome answer! Thank you very much!

Yes, this solves my issue and improved the performance.

And(!) I've learned again something more related to the Active Directory. Thanks! :D

**Comment by stevebauman** [comment]
Thanks so much for your kind words @Sebi94nbg! I'm glad I could help :smile:

If you encounter further issues, feel free to create one and I'll do my best to help out.
