### ISSUE TITLE
Auth::check() fails when using non-default provider in Multiple Providers configurations. Only default provider returns Auth::check() true

### ISSUE THREAD

**Issue by yogeshgupta2931** [Adldap2/Adldap2-Laravel#826]
- Laravel Version: ^6.0
- Adldap2-Laravel Version: ^6.0
- PHP Version: ^7.1.3
- LDAP Type: ActiveDirectory

### Description:
I have a requirement to allow staff login from multiple LDAP servers. Hence I configured multiple connection providers in ldap.config. Since I don't want to sync staff information in my local database, I am using NoDatabaseUserProvider
`'provider' => Adldap\Laravel\Auth\NoDatabaseUserProvider::class,`
Now the problem is, when I try to login using a staff member using the default connection provider , the login works fine. When I change the default connection provider to something set in ldap.config, it authenticates the user but in middleware Auth::check() fails.

```
            $provider = Adldap::getProvider($connectionProviderName);
            
            $user = $provider->search()->users()->find($username);

            $distinguishedname = $user['distinguishedname'][0];
            
            if ( $provider->auth()->attempt($distinguishedname, $password) ) {
                $this->guard()->login($user, false);
                return redirect()->route('dashboard.index');
            } else {
                return redirect()->route('login');
            }
```

### Steps To Reproduce:
1) if $connectionProviderName is the default provider, then staff is taken to dashboard.
2) if the $connectionProviderName is not default provider, then $provider->auth()->.... returns true, staff is taken to dashboard route, but in the middleware Auth::check() fails and hence staff is redirected to login page.

Anyone who experienced similar issue?

**Comment by stevebauman** [comment]
Hi @yogeshgupta2931,

Unfortunately multi-domain authentication is not supported right now. So you will need to use workarounds to get this going.

The implementation you have above will not work. You need to use Laravel's `Auth::attempt()` method, not the Adldap2 provider `auth()->attempt()` method which does not set up a Laravel session. This is described in the documentation:

https://adldap2.github.io/Adldap2-Laravel/#/auth/setup?id=nodatabaseuserprovider

There is a large distinction between the two Adldap2-Laravel authentication providers.

The `DatabaseUserProvider` only requires connectivity once (during authentication). Once a user authenticates, a local database record of the user is created and synchronized. On subsequent requests, the local database record of the synchronized user is retrieved - exactly how standard Laravel database authentication works. No further connectivity is required.

The `NoDatabaseUserProvider` however, requires connectivity to your LDAP server **for every user request**, because it must retrieve the authenticated users information from your server as it is not stored anywhere in your Laravel application.

This means, you must actually set a session variable after your user authenticates with the domain you have configured, and then dynamically retrieve this in your `AppServiceProvider` (or somewhere similar) and override the default configured connection inside your `ldap_auth.php` file.

There are many, many issues already on this (here's a couple: #725, #514, #665, #712), so I am closing this as to not overflow the issues tab.

Thanks!
