### ISSUE TITLE
Allowed memory size on Import Users 

### ISSUE THREAD

**Issue by Vasiliy-Makogon** [Adldap2/Adldap2-Laravel#835]
- Laravel Version: #6.0#
- Adldap2-Laravel Version: #6.0#
- PHP Version: #7.2.21#
- LDAP Type: ActiveDirectory

### Description:

Hi! 
PHP memory_limit	- 512M
I attemp import all users from AD (over 2000 users) and as result -

> PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/dev2.docflow/vendor/adldap2/adldap2/src/Connections/Ldap.php on line 143
> PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/dev2.docflow/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 133

It's normal situation? How much memory is needed for the import to work?

**Comment by stevebauman** [comment]
Hi @Vasiliy-Makogon,

You will need to break your imports into chunks using the `--filter` [command option](https://adldap2.github.io/Adldap2-Laravel/#/auth/importing?id=filter) and then run multiple imports, or utilize a [scope](https://adldap2.github.io/Adldap2-Laravel/#/auth/setup?id=scopes) to limit the number of users you are importing.

Otherwise, you will need to extend your PHP memory limit to bulk import more users.
