### ISSUE TITLE
login fallback not working if ldap server not reachable

### ISSUE THREAD

**Issue by wgmaddin** [Adldap2/Adldap2-Laravel#84]
Hey,

i am not able to get the login fallback working on my dev machine. As long as the LDAP server is reachable via VPN the fallback works without problems if the user isn't a LDAP user. But if the LDAP server is not reachable i always get the following error: 

"Bind to Active Directory failed. Check the login credentials and/or server details. AD said: Can't contact LDAP server"

Please help! Thanks!

**Comment by stevebauman** [comment]
Hi @wgmaddin,

Do you receive the binding failure only when you try to login?

**Comment by wgmaddin** [comment]
Hey @stevebauman,
wow that was fast... :+1: 
Yes, the failure shows up if i try to login.

**Comment by stevebauman** [comment]
Thanks for bring this up @wgmaddin. The issue was that the connection wasn't being checked if it was bound before trying to utilize it. A new release will be out in just a minute with this fix.

Keep in mind, to have fallback enabled, you'll need `auto_connect` set to `false` in your `config/adldap.php` file, and you'll need to try and connect to your provider **before** `Auth::attempt()` is called:

```php
try {
    Adldap::getFacadeRoot()->getProvider('default')->connect();
} catch (Adldap\Exceptions\Auth\BindException $e) {
    // Failed connecting to LDAP server.
}

if (Auth::attempt($credentials)) {
    //
}
```

**Comment by stevebauman** [comment]
New release is out, please update to `v2.0.2` for this fix!

**Comment by wgmaddin** [comment]
@stevebauman, thank you very much for that fast fix! But i'm still having problems if i enable the `bind_user_to_model` option. I think the adldap driver is searching for the corresponding ldap user, but there is no ldap-connection.

**Comment by wgmaddin** [comment]
Okay, i think i got i working. Set `auto_connect` to `false` and established the connection manually with your snippet in the `AuthenticateUsers.php`. 

For getting the `bind_user_to_model` feature to work, i also checked the connection if it was bound before executing the query in `discoverAdldapFromModel` as you did in `retrieveByCredentials`.

Would be nice though, if the `auto_connect` feature could be used in this setup. :)

**Comment by stevebauman** [comment]
> @stevebauman, thank you very much for that fast fix! But i'm still having problems if i enable the bind_user_to_model option. I think the adldap driver is searching for the corresponding ldap user, but there is no ldap-connection.

Yes unfortunately you **need** to connect manually with `auto_connect` turned off if you want login fallback enabled and you do not **always** have a connection to the LDAP server. Otherwise, upon construct, Adldap will connect to your default provider (which won't be available).

> Would be nice though, if the auto_connect feature could be used in this setup. :)

I'll see what I can do! This may get complex, because if `auto_connect` is set to true, the LDAP server **must** be available, allowing querying connections throughout your application without re-connecting every time. If `auto_connect` **isn't** able to connect, how am I going to offer this functionality?
