### ISSUE TITLE
php artisan adldap:import

### ISSUE THREAD

**Issue by rcraig12** [Adldap2/Adldap2-Laravel#888]
- Laravel Version: 7.2.3
- Adldap2-Laravel Version: 6.1.1
- PHP Version: 7.4
- LDAP Type: ActiveDirectory 

### Description:
I have not got a default connection configured as I have multiple domains in a single forest. I can only appear to configure import against one domain. 

What I am looking to do and it may be out of scope is synchronise all users objects from all domains with various attributes so that I can then run reports on AD state. We have integrated with Azure and so it is important to make sure that accounts are configured correctly and track when things are wrong without continually accessing azure for reporting. Doing this means email messaging can be used to alert on misconfigured active directory accounts and license usage of Office 365.

In real terms I am not using this for AD authentication but AD monitoring only.

The ability to run user syncs on the hour for each domain would make my life so much easier 👍

**Comment by stevebauman** [comment]
Hi @rcraig12,

Adldap2-Laravel does not support multiple domains. If you need multiple domain imports, use [LdapRecord-Laravel](https://github.com/DirectoryTree/LdapRecord-Laravel). It also provides examples of running imports on a scheduled interval:

https://ldaprecord.com/docs/laravel/auth/importing/#scheduling-the-command

Also, if you’re looking for a good way to observe changes in your domains, check out [Watchdog](https://github.com/DirectoryTree/Watchdog). It’s an LDAP monitoring and change tracking package using LdapRecord-Laravel. It’s not released yet, but you can get a great idea of how you could build such a system.

Hope this helps! Closing this since LdapRecord provides what you’re asking for, but if you have any questions let me know and I’d be happy to answer them and help get you set up! 👍
