### ISSUE TITLE
Injection not working in 2.0

### ISSUE THREAD

**Issue by jtoler** [Adldap2/Adldap2-Laravel#89]
Since 2.0 I can not get injection working anymore. The code I had working before upgrading to 2.0 no longer works and I get a "undefined class Adldap" error message.

`use Adldap\Contracts\Adldap;`

**Comment by stevebauman** [comment]
Hi @jtoler, I just added this to the upgrade guide, but it was not there previously, apologies!

The interface actually has a new name. It's been switched from `Adldap\Contracts\Adldap`, to: `Adldap\Contracts\AdldapInterface`. This is due to PSR-2 standards.

https://github.com/Adldap2/Adldap2/blob/master/docs/upgrading.md#renamed-adldap-interface
