### ISSUE TITLE
Administrator Username & Password

### ISSUE THREAD

**Issue by triastanto** [Adldap2/Adldap2-Laravel#91]
I have implemented ldap authentication using ldap_connect php built in function and I dont have to provide administrator account credential on application server. In this package, why do we need to provide administrator username & password while I only need to authenticate normal user on AD? My requisites are to provide userprincipalname & their password in order to successfully log into the system.

```php
$ldap = ldap_connect("ldap.example.com");

if ($bind = ldap_bind($ldap, $_POST['username'], $_POST['password'])) {
  // log them in!
} else {
  // error message
}
```

Thanks.

**Comment by stevebauman** [comment]
Hi @triastanto,

You're right. This could be a configurable option.

The reasoning behind requiring administrator credentials is all about flexibility. For example, due to permission restrictions, the bound user might not have permissions to query for users and read their details, so the option `bind_user_to_model` option wouldn't work, since on every request the logged in user is queried for in AD.

Using the administrator credentials just avoids headaches in restrictions, and if you need LDAP operations to be ran **underneath** the logged in user, you're completely able to do so:

```php
$provider = Adldap::getDefaultProvider();

$provider->auth()->bind('jdoe', 'password');

// All LDAP operations are now ran underneath 'jdoe'.
$users = $provider->search()->users()->get();
```

I'll leave this issue open for discussion.

**Comment by imi-info** [comment]
Hi, 
How to disable the requiring administrator credentials by default?
Thank you in advance for your reply.
Best regards

**Comment by stevebauman** [comment]
Hi @imi-info, I'm implementing this as a configurable option now.

**Comment by stevebauman** [comment]
Hey guys, I've actually decided against implementing this. Though I'll continue to leave this issue open for further updates.

Reasoning:

1. Too many features rely on an **already bound** connection. For an example, since the we have configurable username login attributes, we need a bound connection to search for the user, and then retrieve their login attribute, then try binding them to the server. Another example is the `bind_user_to_model` option which sets the AD user model onto the Laravel user model (which wouldn't be possible without binding to the server **before** laravel authentication).

2. This feature would require a new 'minor' version due to the API changes, meaning a new branch to maintain, as well as new documentation to create for the changes. I'm not against this at all, but some examples on implementation and / or API would definitely help.

If you have any ideas that don't require large API changes and you're able to keep the feature set compatible, I'm definitely all ears and will accept PR's.


- Steve

**Comment by jotaelesalinas** [comment]
It looks like this is the main issue regarding the _adminless_ LDAP authentication. Many other issues refer to this one.

So, if I got it right, @stevebauman, with this library, as it is, we are somehow replacing the traditional DB with LDAP. That means that we can create, read, update and delete users as if they were in a "local" database.

Having that in mind, I understand when you say that allowing direct bindings to the logged in user would disable many features and create confusion.

The problem is that in my use case -and many other's- I don't need CRUD on users. I just need to know if the user can log in or not. No user management at all. No roles. No email. No nothing :)

What would you say about creating a second library, e.g. `adldap2-laravel-adminless`? I have never created a service provider sbefore, but I could give it a try. I think it would consist mostly of removing things from this library.

Could you please create  a small guide on how to create alternative auth providers? With things that you have learned the hard way by try and error. It would help me a lot getting started.

**Comment by jotaelesalinas** [comment]
@stevebauman @triastanto @imi-info FYI, if you only need allowed/rejected authentication from LDAP, with no user management and **no admin user required**, this might be useful: [jotaelesalinas/laravel-simple-ldap-auth](https://github.com/jotaelesalinas/laravel-simple-ldap-auth).
